export const flyCategories: string[] = [
  "Systems",
  "Planets",
  "Moons",
  "Asteroids",
  "Comets",
  "Spacecraft",
];

export const flyTargets: { [key: string]: string[] } = {
  Systems: [
    "Sun", // Exception
    "Inner Solar System",
    "Outer Solar System",
    "Earth System",
    "Mars System",
    "Jupiter System",
    "Saturn System",
    "Uranus System",
    "Neptune System",
    "Pluto System",
    "Patroclus and Menoetius",
    "Didymos and Dimorphos",
  ],
  Planets: [
    "Mercury",
    "Venus",
    "Earth",
    "Mars",
    "Jupiter",
    "Saturn",
    "Uranus",
    "Neptune",
    "Ceres",
    "Pluto",
    "Haumea",
    "Eris",
    "Makemake",
  ],
  Moons: [
    "Earth - Moon",
    "Mars - Phobos",
    "Mars - Deimos",
    "Jupiter - Callisto",
    "Jupiter - Europa",
    "Jupiter - Ganymede",
    "Jupiter - Io",
    "Saturn - Dione",
    "Saturn - Enceladus",
    // "Saturn - Hyperion", // Not flying
    "Saturn - Iapetus",
    "Saturn - Mimas",
    "Saturn - Rhea",
    "Saturn - Tethys",
    "Saturn - Titan",
    "Uranus - Ariel",
    "Uranus - Miranda",
    "Uranus - Oberon",
    "Uranus - Titania",
    "Uranus - Umbriel",
    "Neptune - Triton",
    "Pluto - Charon",
    "Pluto - Hydra",
    "Pluto - Kerberos",
    "Pluto - Nix",
    "Pluto - Styx",
    "Haumea - Hiiaka",
    "Haumea - Namaka",
    "Ida - Dactyl",
    "Didymos - Dimorphos",
    "Patroclus - Menoetius",
  ],
  Asteroids: [
    "Psyche (asteroid)",
  "Bennu",
  "Leucus",
  "Zephyr",
  // "Hypnos",
  "Polymele",
  "Icarus",
  // "Geographos",
  "Ryugu",
  // "Apollo",
  // "Midas",
  // "1991 vg",
  // "1993 hd",
  // "1994 cc a",
  // "1996 xb27",
  // "1998 ky26",
  // "1998 ml14",
  // "1998 qe2",
  // "1999 ao10",
  // "1999 cg9",
  // "1999 vx25",
  // "Pallas",
  // "2000 ae205",
  // "2000 lg6",
  // "2000 sg344",
  // "2001 bb16",
  // "2001 fr85",
  // "2001 gp2",
  // "2001 qj142",
  // "2001 sn263 a",
  // "2003 sm84",
  // "2003 uv11",
  // "2003 yn107",
  // "2005 er95",
  // "2005 lc",
  // "2005 qp87",
  // "2005 yu55",
  // "2006 bz147",
  // "2006 jy26",
  // "2006 qq56",
  // "2006 rh120",
  // "2006 ub17",
  // "2007 tf15",
  // "2007 un12",
  // "2007 vu6",
  // "2008 bt2",
  // "2008 cx118",
  // "2008 ea9",
  // "2008 el",
  // "2008 hu4",
  // "2008 jl24",
  // "2008 kt",
  // "2008 tc3",
  // "2008 ts10",
  // "2008 ua202",
  // "2009 bd",
  // "2009 os5",
  // "2009 rt1",
  // "2009 yf",
  // "2010 an61",
  // "2010 dj",
  // "2010 jw34",
  // "2010 tg19",
  // "2010 tn167",
  // "2010 ub",
  "Bacchus",
  "Lutetia",
  // "Adonis",
  // "Tantalus",
  // "Aristaeus",
  // "Kleopatra",
  "Orus",
  // "2007 or10",
  // "Hathor",
  "Ida",
  "Itokawa",
  "Mathilde",
  "Steins",
  // "Juno",
  // "Florence",
  // "Phaethon",
  // "Khufu",
  "Eurybates",
  // "Duende",
  // "Illapa",
  "Vesta",
  // "Wilson",
  // "Toutatis",
  // "Cuno",
  "Eros",
  // "Pan",
  // "Mithra",
  // "Castalia",
  "Arrokoth",
  // "Ptah",
  "Donaldjohanson",
  "Annefrank",
  "Patroclus",
  // "Minos",
  // "Golevka",
  "Didymos",
  // "Moshup",
  // "Hermes",
  "Sedna",
  "Gaspra",
  "Braille",
  "Apophis",
  "Dinkinesh",
  ],
  Comets: [
    "Hartley 2",
    "Tempel 1",
    "Wild 2",
    "Churyumov Gerasimenko",
    "Borrelly",
    // "Oumuamua",
    // "Halley",
    // "C 1995 o1",
    // "C 2010 x1",
    // "C 2012 s1",
    // "C 2013 a1",
    // "C 2019 y4",
    // "C 2020 f3",
  ],
  Spacecraft: [
    // "Ace",
    "Acrimsat",
    // "Aim",
    // "Apollo 15",
    // "Aqua",
    "Artemis 1",
    // "Ascends",
    // "Aura",
    "BioSentinel",
    "CALIPSO",
    "CAPSTONE",
    "Cassini",
    "Chandra X-ray Observatory",
    // "Clarreo",
    "Clementine",
    "CloudSat",
    "Rumba",
    "Salsa",
    "Samba",
    "Tango",
    // "C nofs",
    // "Cygnss 1",
    // "Cygnss 2",
    // "Cygnss 3",
    // "Cygnss 4",
    // "Cygnss 5",
    // "Cygnss 6",
    // "Cygnss 7",
    // "Cygnss 8",
    "DART",
    "Dawn",
    "Deep Impact",
    "Deep Impact Impactor",
    // "Deep impact_impactor_impact_site",
    "Deep Space 1",
    // "Dscovr",
    "EO-1",
    // "Europa clipper",
    // "Explorer 1",
    // "Face",
    // "Fgrst",
    // "Gacm",
    // "Galex",
    "Galileo",
    // "Galileo probe",
    // "Geo cape",
    // "Geotail",
    // "Goes 12",
    // "Goes 13",
    // "Goes 14",
    // "Goes 15",
    // "Gpm",
    "GRACE-1",
    "GRACE-2",
    "GRACE-FO1",
    "GRACE-FO2",
    "GRAIL A",
    "GRAIL B",
    // "Grifex",
    "Hubble Space Telescope",
    "Huygens",
    // "Huygens landing site",
    // "Hyspiri",
    // "Ibex",
    // "Icesat_2",
    // "Image",
    // "Insight",
    // "Insight landing site",
    // "Integral",
    // "Ipex",
    // "Isas",
    "International Space Station (ISS)",
    // "International Space Station (ISS) ecostress",
    // "International Space Station (ISS) emit",
    // "International Space Station (ISS) oco_3",
    // "International Space Station (ISS) rapidscat",
    "IXPE",
    // "Jason-1",
    "Jason-2",
    "Jason-3",
    "Juice",
    "Juno",
    "James Webb Space Telescope",
    "Kepler",
    // "Ladee",
    // "Landsat 5",
    // "Landsat 7",
    // "Landsat 8",
    // "Landsat 9",
    "LCROSS",
    // "LCROSS impact site",
    // "List",
    "Lucy",
    // "Lunar flashlight",
    "Lunar Prospector",
    // "Lunar reconnaissance_orbiter",
    "Magellan",
    "MarCO A",
    "MarCO B",
    // "Mariner 2",
    // "Mars 2020",
    // "Mars 2020 landing site",
    // "Mars climate orbiter",
    // "Mars exploration rover 1",
    // "Mars exploration_rover 1 landing site",
    // "Mars exploration rover 2",
    // "Mars exploration rover 2 landing site",
    // "Mars express",
    "Mars Global Surveyor",
    // "Mars odyssey",
    // "Mars orbiter mission",
    // "Mars pathfinder",
    // "Mars pathfinder landing site",
    // "Mars polar lander",
    // "Mars reconnaissance orbiter",
    // "Mars science laboratory",
    // "Mars science laboratory_landing_site",
    // "Maven",
    // "M cubed",
    // "M cubed 2",
    "MESSENGER",
    // "MESSENGER impact site",
    "MMS 1",
    "MMS 2",
    "MMS 3",
    "MMS 4",
    "NEAR Shoemaker",
    // "NEAR Shoemaker_landing_site",
    "New Horizons",
    // "Nisar",
    // "Noaa 14",
    // "Noaa 15",
    // "Noaa 16",
    // "Noaa 17",
    // "Noaa 18",
    // "Noaa 19",
    // "Nustar",
    "OCO-2",
    "OSIRIS-APEX (OSIRIS-REx)",
    "OSIRIS-REx Sample Return Capsule",
    "Parker Solar Probe",
    // "Path",
    "Philae",
    // "Philae_landing_site",
    // "Phoenix",
    // "Phoenix landing site",
    "Pioneer 10",
    "Pioneer 11",
    // "Polar",
    "Psyche (spacecraft)",
    // "QuikSCAT",
    // "Race",
    // "Raincube",
    // "Rax 2",
    "Van Allen Probe A",
    "Van Allen Probe B",
    "Rosetta",
    // "Rosetta impact site",
    // "Sac d",
    // "Sclp",
    // "Sdo",
    "Sentinel-6 Michael Freilich",
    // "Smap",
    // "Smart 1",
    // "Soho",
    // "Sorce",
    "Spitzer Space Telescope",
    "Stardust",
    // "Stardust src",
    // "Starling 1",
    // "Starling 2",
    // "Starling 3",
    // "Starling 4",
    "STEREO ahead",
    "STEREO behind",
    // "Suomi_npp",
    // "Swift",
    // "Swot",
    // "Tdrs 10",
    // "Tdrs 11",
    // "Tdrs 12",
    // "Tdrs 13",
    // "Tdrs 3",
    // "Tdrs 5",
    // "Tdrs 6",
    // "Tdrs 7",
    // "Tdrs 8",
    // "Tdrs 9",
    // "Terra",
    // "Tess",
    "THEMIS a",
    "ARTEMIS P1",
    "ARTEMIS P2",
    "THEMIS d",
    "THEMIS e",
    // "Timed",
    // "Trace gas orbiter",
    // "Trmm",
    // "Uars",
    "Ulysses",
    // "Venus express",
    // "Viking 1 lander landing site",
    // "Viking 1 orbiter",
    // "Viking 2 lander landing site",
    // "Viking 2 orbiter",
    "Voyager 1",
    "Voyager 2",
    "WIND",
    // "Wise",
    // "Wmap",
  ],
};

export const sortedFlyTargets: {
  [key: string]: { name: string; type: string };
} = {
  sun: { name: "Sun", type: "system" }, // Exception. Don't use goToSystem
  inner_solar_system: { name: "Inner Solar System", type: "system" },
  outer_solar_system: { name: "Outer Solar System", type: "system" },
  earth_system: { name: "Earth ", type: "system" },
  mars_system: { name: "Mars ", type: "system" },
  jupiter_system: { name: "Jupiter ", type: "system" },
  saturn_system: { name: "Saturn ", type: "system" },
  uranus_system: { name: "Uranus ", type: "system" },
  neptune_system: { name: "Neptune ", type: "system" },
  "134340_pluto_barycenter": { name: "Pluto System", type: "system" },
  "617_patroclus_barycenter": {
    name: "Patroclus and Menoetius",
    type: "system",
  },
  "65803_didymos_system": { name: "Didymos and Dimorphos", type: "system" },
  earth: { name: "Earth", type: "planet" },
  mercury: { name: "Mercury", type: "planet" },
  venus: { name: "Venus", type: "planet" },
  mars: { name: "Mars", type: "planet" },
  jupiter: { name: "Jupiter", type: "planet" },
  saturn: { name: "Saturn", type: "planet" },
  uranus: { name: "Uranus", type: "planet" },
  neptune: { name: "Neptune", type: "planet" },
  "1_ceres": { name: "Ceres", type: "planet" },
  "134340_pluto": { name: "Pluto", type: "planet" },
  "136108_haumea": { name: "Haumea", type: "planet" },
  "136199_eris": { name: "Eris", type: "planet" },
  "136472_makemake": { name: "Makemake", type: "planet" },
  "16_psyche": { name: "Psyche (asteroid)", type: "asteroid" },
  "101955_bennu": { name: "Bennu", type: "asteroid" },
  "11351_leucus": { name: "Leucus", type: "asteroid" },
  "12923_zephyr": { name: "Zephyr", type: "asteroid" },
  "14827_hypnos": { name: "Hypnos", type: "asteroid" },
  "15094_polymele": { name: "Polymele", type: "asteroid" },
  "1566_icarus": { name: "Icarus", type: "asteroid" },
  "1620_geographos": { name: "Geographos", type: "asteroid" },
  "162173_ryugu": { name: "Ryugu", type: "asteroid" },
  "1862_apollo": { name: "Apollo", type: "asteroid" },
  "1981_midas": { name: "Midas", type: "asteroid" },
  "1991_vg": { name: "1991 vg", type: "asteroid" },
  "1993_hd": { name: "1993 hd", type: "asteroid" },
  "1994_cc_a": { name: "1994 cc a", type: "asteroid" },
  "1996_xb27": { name: "1996 xb27", type: "asteroid" },
  "1998_ky26": { name: "1998 ky26", type: "asteroid" },
  "1998_ml14": { name: "1998 ml14", type: "asteroid" },
  "1998_qe2": { name: "1998 qe2", type: "asteroid" },
  "1999_ao10": { name: "1999 ao10", type: "asteroid" },
  "1999_cg9": { name: "1999 cg9", type: "asteroid" },
  "1999_vx25": { name: "1999 vx25", type: "asteroid" },
  "2_pallas": { name: "Pallas", type: "asteroid" },
  "2000_ae205": { name: "2000 ae205", type: "asteroid" },
  "2000_lg6": { name: "2000 lg6", type: "asteroid" },
  "2000_sg344": { name: "2000 sg344", type: "asteroid" },
  "2001_bb16": { name: "2001 bb16", type: "asteroid" },
  "2001_fr85": { name: "2001 fr85", type: "asteroid" },
  "2001_gp2": { name: "2001 gp2", type: "asteroid" },
  "2001_qj142": { name: "2001 qj142", type: "asteroid" },
  "2001_sn263_a": { name: "2001 sn263 a", type: "asteroid" },
  "2003_sm84": { name: "2003 sm84", type: "asteroid" },
  "2003_uv11": { name: "2003 uv11", type: "asteroid" },
  "2003_yn107": { name: "2003 yn107", type: "asteroid" },
  "2005_er95": { name: "2005 er95", type: "asteroid" },
  "2005_lc": { name: "2005 lc", type: "asteroid" },
  "2005_qp87": { name: "2005 qp87", type: "asteroid" },
  "2005_yu55": { name: "2005 yu55", type: "asteroid" },
  "2006_bz147": { name: "2006 bz147", type: "asteroid" },
  "2006_jy26": { name: "2006 jy26", type: "asteroid" },
  "2006_qq56": { name: "2006 qq56", type: "asteroid" },
  "2006_rh120": { name: "2006 rh120", type: "asteroid" },
  "2006_ub17": { name: "2006 ub17", type: "asteroid" },
  "2007_tf15": { name: "2007 tf15", type: "asteroid" },
  "2007_un12": { name: "2007 un12", type: "asteroid" },
  "2007_vu6": { name: "2007 vu6", type: "asteroid" },
  "2008_bt2": { name: "2008 bt2", type: "asteroid" },
  "2008_cx118": { name: "2008 cx118", type: "asteroid" },
  "2008_ea9": { name: "2008 ea9", type: "asteroid" },
  "2008_el": { name: "2008 el", type: "asteroid" },
  "2008_hu4": { name: "2008 hu4", type: "asteroid" },
  "2008_jl24": { name: "2008 jl24", type: "asteroid" },
  "2008_kt": { name: "2008 kt", type: "asteroid" },
  "2008_tc3": { name: "2008 tc3", type: "asteroid" },
  "2008_ts10": { name: "2008 ts10", type: "asteroid" },
  "2008_ua202": { name: "2008 ua202", type: "asteroid" },
  "2009_bd": { name: "2009 bd", type: "asteroid" },
  "2009_os5": { name: "2009 os5", type: "asteroid" },
  "2009_rt1": { name: "2009 rt1", type: "asteroid" },
  "2009_yf": { name: "2009 yf", type: "asteroid" },
  "2010_an61": { name: "2010 an61", type: "asteroid" },
  "2010_dj": { name: "2010 dj", type: "asteroid" },
  "2010_jw34": { name: "2010 jw34", type: "asteroid" },
  "2010_tg19": { name: "2010 tg19", type: "asteroid" },
  "2010_tn167": { name: "2010 tn167", type: "asteroid" },
  "2010_ub": { name: "2010 ub", type: "asteroid" },
  "2063_bacchus": { name: "Bacchus", type: "asteroid" },
  "21_lutetia": { name: "Lutetia", type: "asteroid" },
  "2101_adonis": { name: "Adonis", type: "asteroid" },
  "2102_tantalus": { name: "Tantalus", type: "asteroid" },
  "2135_aristaeus": { name: "Aristaeus", type: "asteroid" },
  "216_kleopatra": { name: "Kleopatra", type: "asteroid" },
  "21900_orus": { name: "Orus", type: "asteroid" },
  "225088_2007_or10": { name: "2007 or10", type: "asteroid" },
  "2340_hathor": { name: "Hathor", type: "asteroid" },
  "243_ida": { name: "Ida", type: "asteroid" },
  "25143_itokawa": { name: "Itokawa", type: "asteroid" },
  "253_mathilde": { name: "Mathilde", type: "asteroid" },
  "2867_steins": { name: "Steins", type: "asteroid" },
  "3_juno": { name: "Juno", type: "asteroid" },
  "3122_florence": { name: "Florence", type: "asteroid" },
  "3200_phaethon": { name: "Phaethon", type: "asteroid" },
  "3362_khufu": { name: "Khufu", type: "asteroid" },
  "3548_eurybates": { name: "Eurybates", type: "asteroid" },
  "367943_duende": { name: "Duende", type: "asteroid" },
  "37655_illapa": { name: "Illapa", type: "asteroid" },
  "4_vesta": { name: "Vesta", type: "asteroid" },
  "4015_wilson-harrington": { name: "Wilson", type: "asteroid" },
  "4179_toutatis": { name: "Toutatis", type: "asteroid" },
  "4183_cuno": { name: "Cuno", type: "asteroid" },
  "433_eros": { name: "Eros", type: "asteroid" },
  "4450_pan": { name: "Pan", type: "asteroid" },
  "4486_mithra": { name: "Mithra", type: "asteroid" },
  "4769_castalia": { name: "Castalia", type: "asteroid" },
  "486958_arrokoth": { name: "Arrokoth", type: "asteroid" },
  "5011_ptah": { name: "Ptah", type: "asteroid" },
  "52246_donaldjohanson": { name: "Donaldjohanson", type: "asteroid" },
  "5535_annefrank": { name: "Annefrank", type: "asteroid" },
  "617_patroclus": { name: "Patroclus", type: "asteroid" },
  "6239_minos": { name: "Minos", type: "asteroid" },
  "6489_golevka": { name: "Golevka", type: "asteroid" },
  "65803_didymos": { name: "Didymos", type: "asteroid" },
  "66391_moshup": { name: "Moshup", type: "asteroid" },
  "69230_hermes": { name: "Hermes", type: "asteroid" },
  "90377_sedna": { name: "Sedna", type: "asteroid" },
  "951_gaspra": { name: "Gaspra", type: "asteroid" },
  "9969_braille": { name: "Braille", type: "asteroid" },
  "99942_apophis": { name: "Apophis", type: "asteroid" },
  "152830_dinkinesh": { name: "Dinkinesh", type: "asteroid" },
  moon: { name: "Earth - Moon", type: "moon" },
  phobos: { name: "Mars - Phobos", type: "moon" },
  deimos: { name: "Mars - Deimos", type: "moon" },
  adrastea: { name: "Jupiter - Adrastea", type: "moon" },
  amalthea: { name: "Jupiter - Amalthea", type: "moon" },
  callisto: { name: "Jupiter - Callisto", type: "moon" },
  europa: { name: "Jupiter - Europa", type: "moon" },
  ganymede: { name: "Jupiter - Ganymede", type: "moon" },
  io: { name: "Jupiter - Io", type: "moon" },
  metis: { name: "Jupiter - Metis", type: "moon" },
  thebe: { name: "Jupiter - Thebe", type: "moon" },
  aitne: { name: "Jupiter - Aitne", type: "moon" },
  ananke: { name: "Jupiter - Ananke", type: "moon" },
  aoede: { name: "Jupiter - Aoede", type: "moon" },
  arche: { name: "Jupiter - Arche", type: "moon" },
  autonoe: { name: "Jupiter - Autonoe", type: "moon" },
  callirrhoe: { name: "Jupiter - Callirrhoe", type: "moon" },
  carme: { name: "Jupiter - Carme", type: "moon" },
  carpo: { name: "Jupiter - Carpo", type: "moon" },
  chaldene: { name: "Jupiter - Chaldene", type: "moon" },
  cyllene: { name: "Jupiter - Cyllene", type: "moon" },
  dia: { name: "Jupiter - Dia", type: "moon" },
  eirene: { name: "Jupiter - Eirene", type: "moon" },
  elara: { name: "Jupiter - Elara", type: "moon" },
  erinome: { name: "Jupiter - Erinome", type: "moon" },
  ersa: { name: "Jupiter - Ersa", type: "moon" },
  euanthe: { name: "Jupiter - Euanthe", type: "moon" },
  eukelade: { name: "Jupiter - Eukelade", type: "moon" },
  eupheme: { name: "Jupiter - Eupheme", type: "moon" },
  euporie: { name: "Jupiter - Euporie", type: "moon" },
  eurydome: { name: "Jupiter - Eurydome", type: "moon" },
  harpalyke: { name: "Jupiter - Harpalyke", type: "moon" },
  hegemone: { name: "Jupiter - Hegemone", type: "moon" },
  helike: { name: "Jupiter - Helike", type: "moon" },
  hermippe: { name: "Jupiter - Hermippe", type: "moon" },
  herse: { name: "Jupiter - Herse", type: "moon" },
  himalia: { name: "Jupiter - Himalia", type: "moon" },
  iocaste: { name: "Jupiter - Iocaste", type: "moon" },
  isonoe: { name: "Jupiter - Isonoe", type: "moon" },
  jupiter_li: { name: "Jupiter - Jupiter LI", type: "moon" },
  jupiter_lii: { name: "Jupiter - Jupiter LII", type: "moon" },
  jupiter_liv: { name: "Jupiter - Jupiter LIV", type: "moon" },
  jupiter_lv: { name: "Jupiter - Jupiter LV", type: "moon" },
  jupiter_lvi: { name: "Jupiter - Jupiter LVI", type: "moon" },
  jupiter_lix: { name: "Jupiter - Jupiter LIX", type: "moon" },
  jupiter_lxi: { name: "Jupiter - Jupiter LXI", type: "moon" },
  jupiter_lxiii: { name: "Jupiter - Jupiter LXIII", type: "moon" },
  jupiter_lxiv: { name: "Jupiter - Jupiter LXIV", type: "moon" },
  jupiter_lxvi: { name: "Jupiter - Jupiter LXVI", type: "moon" },
  jupiter_lxvii: { name: "Jupiter - Jupiter LXVII", type: "moon" },
  jupiter_lxviii: { name: "Jupiter - Jupiter LXVIII", type: "moon" },
  jupiter_lxix: { name: "Jupiter - Jupiter LXIX", type: "moon" },
  jupiter_lxx: { name: "Jupiter - Jupiter LXX", type: "moon" },
  jupiter_lxxii: { name: "Jupiter - Jupiter LXXII", type: "moon" },
  kale: { name: "Jupiter - Kale", type: "moon" },
  kallichore: { name: "Jupiter - Kallichore", type: "moon" },
  kalyke: { name: "Jupiter - Kalyke", type: "moon" },
  kore: { name: "Jupiter - Kore", type: "moon" },
  leda: { name: "Jupiter - Leda", type: "moon" },
  lysithea: { name: "Jupiter - Lysithea", type: "moon" },
  megaclite: { name: "Jupiter - Megaclite", type: "moon" },
  mneme: { name: "Jupiter - Mneme", type: "moon" },
  orthosie: { name: "Jupiter - Orthosie", type: "moon" },
  pandia: { name: "Jupiter - Pandia", type: "moon" },
  pasiphae: { name: "Jupiter - Pasiphae", type: "moon" },
  pasithee: { name: "Jupiter - Pasithee", type: "moon" },
  philophrosyne: { name: "Jupiter - Philophrosyne", type: "moon" },
  praxidike: { name: "Jupiter - Praxidike", type: "moon" },
  s_2003_j_2: { name: "Jupiter - S/2003 J 2", type: "moon" },
  s_2003_j_4: { name: "Jupiter - S/2003 J 4", type: "moon" },
  s_2003_j_9: { name: "Jupiter - S/2003 J 9", type: "moon" },
  s_2003_j_10: { name: "Jupiter - S/2003 J 10", type: "moon" },
  s_2003_j_12: { name: "Jupiter - S/2003 J 12", type: "moon" },
  s_2003_j_16: { name: "Jupiter - S/2003 J 16", type: "moon" },
  s_2003_j_23: { name: "Jupiter - S/2003 J 23", type: "moon" },
  s_2003_j_24: { name: "Jupiter - S/2003 J 24", type: "moon" },
  s_2011_j_3: { name: "Jupiter - S/2011 J 3", type: "moon" },
  s_2016_j_3: { name: "Jupiter - S/2016 J 3", type: "moon" },
  s_2016_j_4: { name: "Jupiter - S/2016 J 4", type: "moon" },
  s_2018_j_2: { name: "Jupiter - S/2018 J 2", type: "moon" },
  s_2018_j_3: { name: "Jupiter - S/2018 J 3", type: "moon" },
  s_2018_j_4: { name: "Jupiter - S/2018 J 4", type: "moon" },
  s_2021_j_1: { name: "Jupiter - S/2021 J 1", type: "moon" },
  s_2021_j_2: { name: "Jupiter - S/2021 J 2", type: "moon" },
  s_2021_j_3: { name: "Jupiter - S/2021 J 3", type: "moon" },
  s_2021_j_4: { name: "Jupiter - S/2021 J 4", type: "moon" },
  s_2021_j_5: { name: "Jupiter - S/2021 J 5", type: "moon" },
  s_2021_j_6: { name: "Jupiter - S/2021 J 6", type: "moon" },
  s_2022_j_1: { name: "Jupiter - S/2022 J 1", type: "moon" },
  s_2022_j_2: { name: "Jupiter - S/2022 J 2", type: "moon" },
  s_2022_j_3: { name: "Jupiter - S/2022 J 3", type: "moon" },
  sinope: { name: "Jupiter - Sinope", type: "moon" },
  sponde: { name: "Jupiter - Sponde", type: "moon" },
  taygete: { name: "Jupiter - Taygete", type: "moon" },
  thelxinoe: { name: "Jupiter - Thelxinoe", type: "moon" },
  themisto: { name: "Jupiter - THEMISto", type: "moon" },
  thyone: { name: "Jupiter - Thyone", type: "moon" },
  valetudo: { name: "Jupiter - Valetudo", type: "moon" },
  dione: { name: "Saturn - Dione", type: "moon" },
  enceladus: { name: "Saturn - Enceladus", type: "moon" },
  hyperion: { name: "Saturn - Hyperion", type: "moon" },
  iapetus: { name: "Saturn - Iapetus", type: "moon" },
  mimas: { name: "Saturn - Mimas", type: "moon" },
  rhea: { name: "Saturn - Rhea", type: "moon" },
  tethys: { name: "Saturn - Tethys", type: "moon" },
  titan: { name: "Saturn - Titan", type: "moon" },
  aegaeon: { name: "Saturn - Aegaeon", type: "moon" },
  aegir: { name: "Saturn - Aegir", type: "moon" },
  albiorix: { name: "Saturn - Albiorix", type: "moon" },
  alvaldi: { name: "Saturn - Alvaldi", type: "moon" },
  angrboda: { name: "Saturn - Angrboda", type: "moon" },
  anthe: { name: "Saturn - Anthe", type: "moon" },
  atlas: { name: "Saturn - Atlas", type: "moon" },
  bebhionn: { name: "Saturn - Bebhionn", type: "moon" },
  beli: { name: "Saturn - Beli", type: "moon" },
  bergelmir: { name: "Saturn - Bergelmir", type: "moon" },
  bestla: { name: "Saturn - Bestla", type: "moon" },
  calypso: { name: "Saturn - Calypso", type: "moon" },
  daphnis: { name: "Saturn - Daphnis", type: "moon" },
  eggther: { name: "Saturn - Eggther", type: "moon" },
  epimetheus: { name: "Saturn - Epimetheus", type: "moon" },
  erriapus: { name: "Saturn - Erriapus", type: "moon" },
  farbauti: { name: "Saturn - Farbauti", type: "moon" },
  fenrir: { name: "Saturn - Fenrir", type: "moon" },
  fornjot: { name: "Saturn - Fornjot", type: "moon" },
  geirrod: { name: "Saturn - Geirrod", type: "moon" },
  gerd: { name: "Saturn - Gerd", type: "moon" },
  greip: { name: "Saturn - Greip", type: "moon" },
  gridr: { name: "Saturn - Gridr", type: "moon" },
  gunnlod: { name: "Saturn - Gunnlod", type: "moon" },
  hati: { name: "Saturn - Hati", type: "moon" },
  helene: { name: "Saturn - Helene", type: "moon" },
  hyrrokkin: { name: "Saturn - Hyrrokkin", type: "moon" },
  ijiraq: { name: "Saturn - Ijiraq", type: "moon" },
  janus: { name: "Saturn - Janus", type: "moon" },
  jarnsaxa: { name: "Saturn - Jarnsaxa", type: "moon" },
  kari: { name: "Saturn - Kari", type: "moon" },
  kiviuq: { name: "Saturn - Kiviuq", type: "moon" },
  loge: { name: "Saturn - Loge", type: "moon" },
  methone: { name: "Saturn - Methone", type: "moon" },
  mundilfari: { name: "Saturn - Mundilfari", type: "moon" },
  narvi: { name: "Saturn - Narvi", type: "moon" },
  paaliaq: { name: "Saturn - Paaliaq", type: "moon" },
  pallene: { name: "Saturn - Pallene", type: "moon" },
  pan: { name: "Saturn - Pan", type: "moon" },
  pandora: { name: "Saturn - Pandora", type: "moon" },
  phoebe: { name: "Saturn - Phoebe", type: "moon" },
  polydeuces: { name: "Saturn - Polydeuces", type: "moon" },
  prometheus: { name: "Saturn - Prometheus", type: "moon" },
  s_2004_s_7: { name: "Saturn - S/2004 S 7", type: "moon" },
  s_2004_s_12: { name: "Saturn - S/2004 S 12", type: "moon" },
  s_2004_s_13: { name: "Saturn - S/2004 S 13", type: "moon" },
  s_2004_s_17: { name: "Saturn - S/2004 S 17", type: "moon" },
  s_2004_s_21: { name: "Saturn - S/2004 S 21", type: "moon" },
  s_2004_s_24: { name: "Saturn - S/2004 S 24", type: "moon" },
  s_2004_s_28: { name: "Saturn - S/2004 S 28", type: "moon" },
  s_2004_s_31: { name: "Saturn - S/2004 S 31", type: "moon" },
  s_2004_s_36: { name: "Saturn - S/2004 S 36", type: "moon" },
  s_2004_s_37: { name: "Saturn - S/2004 S 37", type: "moon" },
  s_2004_s_39: { name: "Saturn - S/2004 S 39", type: "moon" },
  s_2006_s_1: { name: "Saturn - S/2006 S 1", type: "moon" },
  s_2006_s_3: { name: "Saturn - S/2006 S 3", type: "moon" },
  s_2007_s_2: { name: "Saturn - S/2007 S 2", type: "moon" },
  s_2007_s_3: { name: "Saturn - S/2007 S 3", type: "moon" },
  s_2009_s_1: { name: "Saturn - S/2009 S 1", type: "moon" },
  s_2019_s_1: { name: "Saturn - S/2019 S 1", type: "moon" },
  saturn_lviii: { name: "Saturn - Saturn_lviii", type: "moon" },
  saturn_lx: { name: "Saturn - Saturn_lx", type: "moon" },
  saturn_lxiv: { name: "Saturn - Saturn_lxiv", type: "moon" },
  siarnaq: { name: "Saturn - Siarnaq", type: "moon" },
  skathi: { name: "Saturn - Skathi", type: "moon" },
  skoll: { name: "Saturn - Skoll", type: "moon" },
  skrymir: { name: "Saturn - Skrymir", type: "moon" },
  surtur: { name: "Saturn - Surtur", type: "moon" },
  suttungr: { name: "Saturn - Suttungr", type: "moon" },
  tarqeq: { name: "Saturn - Tarqeq", type: "moon" },
  tarvos: { name: "Saturn - Tarvos", type: "moon" },
  telesto: { name: "Saturn - Telesto", type: "moon" },
  thiazzi: { name: "Saturn - Thiazzi", type: "moon" },
  thrymr: { name: "Saturn - Thrymr", type: "moon" },
  ymir: { name: "Saturn - Ymir", type: "moon" },
  s_2004_s_40: { name: "Saturn - S/2004 S 40", type: "moon" },
  s_2004_s_41: { name: "Saturn - S/2004 S 41", type: "moon" },
  s_2004_s_42: { name: "Saturn - S/2004 S 42", type: "moon" },
  s_2004_s_43: { name: "Saturn - S/2004 S 43", type: "moon" },
  s_2004_s_44: { name: "Saturn - S/2004 S 44", type: "moon" },
  s_2004_s_45: { name: "Saturn - S/2004 S 45", type: "moon" },
  s_2004_s_46: { name: "Saturn - S/2004 S 46", type: "moon" },
  s_2004_s_47: { name: "Saturn - S/2004 S 47", type: "moon" },
  s_2004_s_48: { name: "Saturn - S/2004 S 48", type: "moon" },
  s_2004_s_49: { name: "Saturn - S/2004 S 49", type: "moon" },
  s_2004_s_50: { name: "Saturn - S/2004 S 50", type: "moon" },
  s_2004_s_51: { name: "Saturn - S/2004 S 51", type: "moon" },
  s_2004_s_52: { name: "Saturn - S/2004 S 52", type: "moon" },
  s_2004_s_53: { name: "Saturn - S/2004 S 53", type: "moon" },
  s_2005_s_4: { name: "Saturn - S/2005 S 4", type: "moon" },
  s_2005_s_5: { name: "Saturn - S/2005 S 5", type: "moon" },
  s_2006_s_10: { name: "Saturn - S/2006 S 10", type: "moon" },
  s_2006_s_11: { name: "Saturn - S/2006 S 11", type: "moon" },
  s_2006_s_12: { name: "Saturn - S/2006 S 12", type: "moon" },
  s_2006_s_13: { name: "Saturn - S/2006 S 13", type: "moon" },
  s_2006_s_14: { name: "Saturn - S/2006 S 14", type: "moon" },
  s_2006_s_15: { name: "Saturn - S/2006 S 15", type: "moon" },
  s_2006_s_16: { name: "Saturn - S/2006 S 16", type: "moon" },
  s_2006_s_17: { name: "Saturn - S/2006 S 17", type: "moon" },
  s_2006_s_18: { name: "Saturn - S/2006 S 18", type: "moon" },
  s_2006_s_19: { name: "Saturn - S/2006 S 19", type: "moon" },
  s_2006_s_20: { name: "Saturn - S/2006 S 20", type: "moon" },
  s_2006_s_9: { name: "Saturn - S/2006 S 9", type: "moon" },
  s_2007_s_5: { name: "Saturn - S/2007 S 5", type: "moon" },
  s_2007_s_6: { name: "Saturn - S/2007 S 6", type: "moon" },
  s_2007_s_7: { name: "Saturn - S/2007 S 7", type: "moon" },
  s_2007_s_8: { name: "Saturn - S/2007 S 8", type: "moon" },
  s_2007_s_9: { name: "Saturn - S/2007 S 9", type: "moon" },
  s_2019_s_10: { name: "Saturn - S/2019 S 10", type: "moon" },
  s_2019_s_11: { name: "Saturn - S/2019 S 11", type: "moon" },
  s_2019_s_12: { name: "Saturn - S/2019 S 12", type: "moon" },
  s_2019_s_13: { name: "Saturn - S/2019 S 13", type: "moon" },
  s_2019_s_14: { name: "Saturn - S/2019 S 14", type: "moon" },
  s_2019_s_15: { name: "Saturn - S/2019 S 15", type: "moon" },
  s_2019_s_16: { name: "Saturn - S/2019 S 16", type: "moon" },
  s_2019_s_17: { name: "Saturn - S/2019 S 17", type: "moon" },
  s_2019_s_18: { name: "Saturn - S/2019 S 18", type: "moon" },
  s_2019_s_19: { name: "Saturn - S/2019 S 19", type: "moon" },
  s_2019_s_2: { name: "Saturn - S/2019 S 2", type: "moon" },
  s_2019_s_20: { name: "Saturn - S/2019 S 20", type: "moon" },
  s_2019_s_21: { name: "Saturn - S/2019 S 21", type: "moon" },
  s_2019_s_3: { name: "Saturn - S/2019 S 3", type: "moon" },
  s_2019_s_4: { name: "Saturn - S/2019 S 4", type: "moon" },
  s_2019_s_5: { name: "Saturn - S/2019 S 5", type: "moon" },
  s_2019_s_6: { name: "Saturn - S/2019 S 6", type: "moon" },
  s_2019_s_7: { name: "Saturn - S/2019 S 7", type: "moon" },
  s_2019_s_8: { name: "Saturn - S/2019 S 8", type: "moon" },
  s_2019_s_9: { name: "Saturn - S/2019 S 9", type: "moon" },
  s_2020_s_1: { name: "Saturn - S/2020 S 1", type: "moon" },
  s_2020_s_10: { name: "Saturn - S/2020 S 10", type: "moon" },
  s_2020_s_2: { name: "Saturn - S/2020 S 2", type: "moon" },
  s_2020_s_3: { name: "Saturn - S/2020 S 3", type: "moon" },
  s_2020_s_4: { name: "Saturn - S/2020 S 4", type: "moon" },
  s_2020_s_5: { name: "Saturn - S/2020 S 5", type: "moon" },
  s_2020_s_6: { name: "Saturn - S/2020 S 6", type: "moon" },
  s_2020_s_7: { name: "Saturn - S/2020 S 7", type: "moon" },
  s_2020_s_8: { name: "Saturn - S/2020 S 8", type: "moon" },
  s_2020_s_9: { name: "Saturn - S/2020 S 9", type: "moon" },
  ariel: { name: "Uranus - Ariel", type: "moon" },
  miranda: { name: "Uranus - Miranda", type: "moon" },
  oberon: { name: "Uranus - Oberon", type: "moon" },
  titania: { name: "Uranus - Titania", type: "moon" },
  umbriel: { name: "Uranus - Umbriel", type: "moon" },
  belinda: { name: "Uranus - Belinda", type: "moon" },
  bianca: { name: "Uranus - Bianca", type: "moon" },
  caliban: { name: "Uranus - Caliban", type: "moon" },
  cordelia: { name: "Uranus - Cordelia", type: "moon" },
  cressida: { name: "Uranus - Cressida", type: "moon" },
  cupid: { name: "Uranus - Cupid", type: "moon" },
  desdemona: { name: "Uranus - Desdemona", type: "moon" },
  ferdinand: { name: "Uranus - Ferdinand", type: "moon" },
  francisco: { name: "Uranus - Francisco", type: "moon" },
  juliet: { name: "Uranus - Juliet", type: "moon" },
  mab: { name: "Uranus - Mab", type: "moon" },
  margaret: { name: "Uranus - Margaret", type: "moon" },
  ophelia: { name: "Uranus - Ophelia", type: "moon" },
  perdita: { name: "Uranus - Perdita", type: "moon" },
  portia: { name: "Uranus - Portia", type: "moon" },
  prospero: { name: "Uranus - Prospero", type: "moon" },
  puck: { name: "Uranus - Puck", type: "moon" },
  rosalind: { name: "Uranus - Rosalind", type: "moon" },
  setebos: { name: "Uranus - Setebos", type: "moon" },
  stephano: { name: "Uranus - Stephano", type: "moon" },
  sycorax: { name: "Uranus - Sycorax", type: "moon" },
  trinculo: { name: "Uranus - Trinculo", type: "moon" },
  despina: { name: "Neptune - Despina", type: "moon" },
  galatea: { name: "Neptune - Galatea", type: "moon" },
  halimede: { name: "Neptune - Halimede", type: "moon" },
  hippocamp: { name: "Neptune - Hippocamp", type: "moon" },
  laomedeia: { name: "Neptune - Laomedeia", type: "moon" },
  larissa: { name: "Neptune - Larissa", type: "moon" },
  naiad: { name: "Neptune - Naiad", type: "moon" },
  nereid: { name: "Neptune - Nereid", type: "moon" },
  neso: { name: "Neptune - Neso", type: "moon" },
  proteus: { name: "Neptune - Proteus", type: "moon" },
  psamathe: { name: "Neptune - Psamathe", type: "moon" },
  sao: { name: "Neptune - Sao", type: "moon" },
  thalassa: { name: "Neptune - Thalassa", type: "moon" },
  triton: { name: "Neptune - Triton", type: "moon" },
  charon: { name: "Pluto - Charon", type: "moon" },
  hydra: { name: "Pluto - Hydra", type: "moon" },
  kerberos: { name: "Pluto - Kerberos", type: "moon" },
  nix: { name: "Pluto - Nix", type: "moon" },
  styx: { name: "Pluto - Styx", type: "moon" },
  dactyl: { name: "Ida - Dactyl", type: "moon" },
  dimorphos_system: { name: "Didymos and Dimorphos", type: "moon" },
  hiiaka: { name: "Haumea - Hiiaka", type: "moon" },
  namaka: { name: "Haumea - Namaka", type: "moon" },
  menoetius: { name: "Patroclus - Menoetius", type: "moon" },
  "1i_oumuamua": { name: "Oumuamua", type: "comet" },
  "1p_halley": { name: "Halley", type: "comet" },
  "103p_hartley_2": { name: "Hartley 2", type: "comet" },
  "9p_tempel_1": { name: "Tempel 1", type: "comet" },
  "81p_wild_2": { name: "Wild 2", type: "comet" },
  "67p_churyumov_gerasimenko": { name: "Churyumov Gerasimenko", type: "comet" },
  "19p_borrelly": { name: "Borrelly", type: "comet" },
  c_1995_o1: { name: "C 1995 o1", type: "comet" },
  c_2010_x1: { name: "C 2010 x1", type: "comet" },
  c_2012_s1: { name: "C 2012 s1", type: "comet" },
  c_2013_a1: { name: "C 2013 a1", type: "comet" },
  c_2019_y4: { name: "C 2019 y4", type: "comet" },
  c_2020_f3: { name: "C 2020 f3", type: "comet" },
  sc_3d_winds: { name: "3d winds", type: "spacecraft" },
  sc_ace: { name: "Ace", type: "spacecraft" },
  sc_acrimsat: { name: "Acrimsat", type: "spacecraft" },
  sc_aim: { name: "Aim", type: "spacecraft" },
  sc_aqua: { name: "Aqua", type: "spacecraft" },
  sc_ascends: { name: "Ascends", type: "spacecraft" },
  sc_aura: { name: "Aura", type: "spacecraft" },
  sc_c_nofs: { name: "C nofs", type: "spacecraft" },
  sc_calipso: { name: "CALIPSO", type: "spacecraft" },
  sc_chandra: { name: "Chandra X-ray Observatory", type: "spacecraft" },
  sc_clarreo: { name: "Clarreo", type: "spacecraft" },
  sc_cloudsat: { name: "CloudSat", type: "spacecraft" },
  sc_cluster_ii_fm5: { name: "Rumba", type: "spacecraft" },
  sc_cluster_ii_fm6: { name: "Salsa", type: "spacecraft" },
  sc_cluster_ii_fm7: { name: "Samba", type: "spacecraft" },
  sc_cluster_ii_fm8: { name: "Tango", type: "spacecraft" },
  sc_cygnss_1: { name: "Cygnss 1", type: "spacecraft" },
  sc_cygnss_2: { name: "Cygnss 2", type: "spacecraft" },
  sc_cygnss_3: { name: "Cygnss 3", type: "spacecraft" },
  sc_cygnss_4: { name: "Cygnss 4", type: "spacecraft" },
  sc_cygnss_5: { name: "Cygnss 5", type: "spacecraft" },
  sc_cygnss_6: { name: "Cygnss 6", type: "spacecraft" },
  sc_cygnss_7: { name: "Cygnss 7", type: "spacecraft" },
  sc_cygnss_8: { name: "Cygnss 8", type: "spacecraft" },
  sc_dscovr: { name: "Dscovr", type: "spacecraft" },
  sc_eo_1: { name: "EO-1", type: "spacecraft" },
  sc_explorer_1: { name: "Explorer 1", type: "spacecraft" },
  sc_face: { name: "Face", type: "spacecraft" },
  sc_fgrst: { name: "Fgrst", type: "spacecraft" },
  sc_gacm: { name: "Gacm", type: "spacecraft" },
  sc_galex: { name: "Galex", type: "spacecraft" },
  sc_geo_cape: { name: "Geo cape", type: "spacecraft" },
  sc_geotail: { name: "Geotail", type: "spacecraft" },
  sc_goes_12: { name: "Goes 12", type: "spacecraft" },
  sc_goes_13: { name: "Goes 13", type: "spacecraft" },
  sc_goes_14: { name: "Goes 14", type: "spacecraft" },
  sc_goes_15: { name: "Goes 15", type: "spacecraft" },
  sc_gpm: { name: "Gpm", type: "spacecraft" },
  sc_grace_1: { name: "GRACE-1", type: "spacecraft" },
  sc_grace_2: { name: "GRACE-2", type: "spacecraft" },
  sc_grace_fo1: { name: "GRACE-FO1", type: "spacecraft" },
  sc_grace_fo2: { name: "GRACE-FO2", type: "spacecraft" },
  sc_grifex: { name: "Grifex", type: "spacecraft" },
  sc_hubble_space_telescope: {
    name: "Hubble Space Telescope",
    type: "spacecraft",
  },
  sc_hyspiri: { name: "Hyspiri", type: "spacecraft" },
  sc_ibex: { name: "Ibex", type: "spacecraft" },
  sc_icesat_2: { name: "Icesat_2", type: "spacecraft" },
  sc_image: { name: "Image", type: "spacecraft" },
  sc_integral: { name: "Integral", type: "spacecraft" },
  sc_ipex: { name: "Ipex", type: "spacecraft" },
  sc_isas: { name: "Isas", type: "spacecraft" },
  sc_iss: { name: "International Space Station (ISS)", type: "spacecraft" },
  sc_ixpe: { name: "IXPE", type: "spacecraft" },
  sc_jason_1: { name: "Jason-1", type: "spacecraft" },
  sc_jason_2: { name: "Jason-2", type: "spacecraft" },
  sc_jason_3: { name: "Jason-3", type: "spacecraft" },
  sc_juno: { name: "Juno", type: "spacecraft" },
  sc_jwst: { name: "James Webb Space Telescope", type: "spacecraft" },
  sc_landsat_5: { name: "Landsat 5", type: "spacecraft" },
  sc_landsat_7: { name: "Landsat 7", type: "spacecraft" },
  sc_landsat_8: { name: "Landsat 8", type: "spacecraft" },
  sc_landsat_9: { name: "Landsat 9", type: "spacecraft" },
  sc_m_cubed: { name: "M cubed", type: "spacecraft" },
  sc_mcubed_2: { name: "M cubed 2", type: "spacecraft" },
  sc_mms_1: { name: "MMS 1", type: "spacecraft" },
  sc_mms_2: { name: "MMS 2", type: "spacecraft" },
  sc_mms_3: { name: "MMS 3", type: "spacecraft" },
  sc_mms_4: { name: "MMS 4", type: "spacecraft" },
  sc_nisar: { name: "Nisar", type: "spacecraft" },
  sc_noaa_14: { name: "Noaa 14", type: "spacecraft" },
  sc_noaa_15: { name: "Noaa 15", type: "spacecraft" },
  sc_noaa_16: { name: "Noaa 16", type: "spacecraft" },
  sc_noaa_17: { name: "Noaa 17", type: "spacecraft" },
  sc_noaa_18: { name: "Noaa 18", type: "spacecraft" },
  sc_noaa_19: { name: "Noaa 19", type: "spacecraft" },
  sc_nustar: { name: "Nustar", type: "spacecraft" },
  sc_oco_2: { name: "OCO-2", type: "spacecraft" },
  sc_path: { name: "Path", type: "spacecraft" },
  sc_polar: { name: "Polar", type: "spacecraft" },
  sc_psyche: { name: "Psyche (spacecraft)", type: "spacecraft" },
  sc_quikscat: { name: "QuikSCAT", type: "spacecraft" },
  sc_race: { name: "Race", type: "spacecraft" },
  sc_raincube: { name: "Raincube", type: "spacecraft" },
  sc_rax_2: { name: "Rax 2", type: "spacecraft" },
  sc_rbsp_a: { name: "Van Allen Probe A", type: "spacecraft" },
  sc_rbsp_b: { name: "Van Allen Probe B", type: "spacecraft" },
  sc_sac_d: { name: "Sac d", type: "spacecraft" },
  sc_sclp: { name: "Sclp", type: "spacecraft" },
  sc_sdo: { name: "Sdo", type: "spacecraft" },
  sc_sentinel_6: { name: "Sentinel-6 Michael Freilich", type: "spacecraft" },
  sc_smap: { name: "Smap", type: "spacecraft" },
  sc_soho: { name: "Soho", type: "spacecraft" },
  sc_sorce: { name: "Sorce", type: "spacecraft" },
  sc_starling_1: { name: "Starling 1", type: "spacecraft" },
  sc_starling_2: { name: "Starling 2", type: "spacecraft" },
  sc_starling_3: { name: "Starling 3", type: "spacecraft" },
  sc_starling_4: { name: "Starling 4", type: "spacecraft" },
  sc_suomi_npp: { name: "Suomi_npp", type: "spacecraft" },
  sc_swift: { name: "Swift", type: "spacecraft" },
  sc_swot: { name: "Swot", type: "spacecraft" },
  sc_tdrs_3: { name: "Tdrs 3", type: "spacecraft" },
  sc_tdrs_5: { name: "Tdrs 5", type: "spacecraft" },
  sc_tdrs_6: { name: "Tdrs 6", type: "spacecraft" },
  sc_tdrs_7: { name: "Tdrs 7", type: "spacecraft" },
  sc_tdrs_8: { name: "Tdrs 8", type: "spacecraft" },
  sc_tdrs_9: { name: "Tdrs 9", type: "spacecraft" },
  sc_tdrs_10: { name: "Tdrs 10", type: "spacecraft" },
  sc_tdrs_11: { name: "Tdrs 11", type: "spacecraft" },
  sc_tdrs_12: { name: "Tdrs 12", type: "spacecraft" },
  sc_tdrs_13: { name: "Tdrs 13", type: "spacecraft" },
  sc_terra: { name: "Terra", type: "spacecraft" },
  sc_tess: { name: "Tess", type: "spacecraft" },
  sc_themis_a: { name: "THEMIS a", type: "spacecraft" },
  sc_themis_d: { name: "THEMIS d", type: "spacecraft" },
  sc_themis_e: { name: "THEMIS e", type: "spacecraft" },
  sc_timed: { name: "Timed", type: "spacecraft" },
  sc_trmm: { name: "Trmm", type: "spacecraft" },
  sc_uars: { name: "Uars", type: "spacecraft" },
  sc_wind: { name: "WIND", type: "spacecraft" },
  sc_wise: { name: "Wise", type: "spacecraft" },
  sc_apollo_15: { name: "Apollo 15", type: "spacecraft" },
  sc_artemis_1: { name: "Artemis 1", type: "spacecraft" },
  sc_capstone: { name: "CAPSTONE", type: "spacecraft" },
  sc_clementine: { name: "Clementine", type: "spacecraft" },
  sc_grail_a: { name: "GRAIL A", type: "spacecraft" },
  sc_grail_b: { name: "GRAIL B", type: "spacecraft" },
  sc_ladee: { name: "Ladee", type: "spacecraft" },
  sc_lcross: { name: "LCROSS", type: "spacecraft" },
  sc_lcross_impact_site: { name: "LCROSS impact site", type: "spacecraft" },
  sc_lunar_flashlight: { name: "Lunar flashlight", type: "spacecraft" },
  sc_lunar_prospector: { name: "Lunar Prospector", type: "spacecraft" },
  sc_lunar_reconnaissance_orbiter: {
    name: "Lunar reconnaissance_orbiter",
    type: "spacecraft",
  },
  sc_smart_1: { name: "Smart 1", type: "spacecraft" },
  sc_themis_b: { name: "ARTEMIS P1", type: "spacecraft" },
  sc_themis_c: { name: "ARTEMIS P2", type: "spacecraft" },
  sc_mars_2020: { name: "Mars 2020", type: "spacecraft" },
  sc_mars_2020_landing_site: {
    name: "Mars 2020 landing site",
    type: "spacecraft",
  },
  sc_mars_science_laboratory: {
    name: "Mars science laboratory",
    type: "spacecraft",
  },
  sc_mars_science_laboratory_landing_site: {
    name: "Mars science laboratory_landing_site",
    type: "spacecraft",
  },
  sc_insight: { name: "Insight", type: "spacecraft" },
  sc_insight_landing_site: { name: "Insight landing site", type: "spacecraft" },
  sc_marco_a: { name: "MarCO A", type: "spacecraft" },
  sc_marco_b: { name: "MarCO B", type: "spacecraft" },
  sc_mars_odyssey: { name: "Mars odyssey", type: "spacecraft" },
  sc_mars_reconnaissance_orbiter: {
    name: "Mars reconnaissance orbiter",
    type: "spacecraft",
  },
  sc_maven: { name: "Maven", type: "spacecraft" },
  sc_mars_express: { name: "Mars express", type: "spacecraft" },
  sc_phoenix: { name: "Phoenix", type: "spacecraft" },
  sc_phoenix_landing_site: { name: "Phoenix landing site", type: "spacecraft" },
  sc_trace_gas_orbiter: { name: "Trace gas orbiter", type: "spacecraft" },
  sc_mars_orbiter_mission: { name: "Mars orbiter mission", type: "spacecraft" },
  sc_mars_global_surveyor: { name: "Mars Global Surveyor", type: "spacecraft" },
  sc_mars_climate_orbiter: { name: "Mars climate orbiter", type: "spacecraft" },
  sc_mars_pathfinder: { name: "Mars pathfinder", type: "spacecraft" },
  sc_mars_pathfinder_landing_site: {
    name: "Mars pathfinder landing site",
    type: "spacecraft",
  },
  sc_mars_polar_lander: { name: "Mars polar lander", type: "spacecraft" },
  sc_viking_2_orbiter: { name: "Viking 2 orbiter", type: "spacecraft" },
  sc_viking_2_lander_landing_site: {
    name: "Viking 2 lander landing site",
    type: "spacecraft",
  },
  sc_messenger: { name: "MESSENGER", type: "spacecraft" },
  sc_messenger_impact_site: {
    name: "MESSENGER impact site",
    type: "spacecraft",
  },
  sc_cassini: { name: "Cassini", type: "spacecraft" },
  sc_europa_clipper: { name: "Europa clipper", type: "spacecraft" },
  sc_galileo: { name: "Galileo", type: "spacecraft" },
  sc_galileo_probe: { name: "Galileo probe", type: "spacecraft" },
  sc_huygens: { name: "Huygens", type: "spacecraft" },
  sc_huygens_landing_site: { name: "Huygens landing site", type: "spacecraft" },
  sc_juice: { name: "Juice", type: "spacecraft" },
  sc_pioneer_10: { name: "Pioneer 10", type: "spacecraft" },
  sc_pioneer_11: { name: "Pioneer 11", type: "spacecraft" },
  sc_voyager_1: { name: "Voyager 1", type: "spacecraft" },
  sc_voyager_2: { name: "Voyager 2", type: "spacecraft" },
  sc_dart: { name: "DART", type: "spacecraft" },
  sc_dawn: { name: "Dawn", type: "spacecraft" },
  sc_deep_impact: { name: "Deep impact", type: "spacecraft" },
  sc_deep_impact_impactor: { name: "Deep Impact Impactor", type: "spacecraft" },
  sc_deep_impact_impactor_impact_site: {
    name: "Deep impact_impactor_impact_site",
    type: "spacecraft",
  },
  sc_deep_space_1: { name: "Deep Space 1", type: "spacecraft" },
  sc_near_shoemaker: { name: "NEAR Shoemaker", type: "spacecraft" },
  sc_near_shoemaker_landing_site: {
    name: "NEAR Shoemaker_landing_site",
    type: "spacecraft",
  },
  sc_lucy: { name: "Lucy", type: "spacecraft" },
  sc_new_horizons: { name: "New Horizons", type: "spacecraft" },
  sc_rosetta: { name: "Rosetta", type: "spacecraft" },
  sc_rosetta_impact_site: { name: "Rosetta impact site", type: "spacecraft" },
  sc_osiris_rex: { name: "OSIRIS-APEX (OSIRIS-REx)", type: "spacecraft" },
  sc_osiris_rex_src: { name: "OSIRIS-REx Sample Return Capsule", type: "spacecraft" },
  sc_philae: { name: "Philae", type: "spacecraft" },
  sc_philae_landing_site: { name: "Philae_landing_site", type: "spacecraft" },
  sc_biosentinel: { name: "BioSentinel", type: "spacecraft" },
  sc_kepler_space_telescope: {
    name: "Kepler",
    type: "spacecraft",
  },
  sc_mariner_2: { name: "Mariner 2", type: "spacecraft" },
  sc_parker_solar_probe: { name: "Parker Solar Probe", type: "spacecraft" },
  sc_spitzer: { name: "Spitzer Space Telescope", type: "spacecraft" },
  sc_stereo_ahead: { name: "STEREO ahead", type: "spacecraft" },
  sc_stereo_behind: { name: "STEREO behind", type: "spacecraft" },
  sc_ulysses: { name: "Ulysses", type: "spacecraft" },
  sc_wmap: { name: "Wmap", type: "spacecraft" },
  sc_magellan: { name: "Magellan", type: "spacecraft" },
  sc_venus_express: { name: "Venus express", type: "spacecraft" },
};

export const targetToId: { [key: string]: string } = {
  ////////////////////////////////////////////////////
  //                     Systems                    //
  ////////////////////////////////////////////////////
  Sun: "sun",
  "Inner Solar System": "inner_solar_system",
  "Outer Solar System": "outer_solar_system",
  "Earth System": "earth_system",
  "Mars System": "mars_system",
  "Jupiter System": "jupiter_system",
  "Saturn System": "saturn_system",
  "Uranus System": "uranus_system",
  "Neptune System": "neptune_system",
  "Pluto System": "134340_pluto_barycenter",
  "Patroclus and Menoetius": "617_patroclus_barycenter",
  "Didymos and Dimorphos": "65803_didymos_system",
  ////////////////////////////////////////////////////
  //                     Planets                    //
  ////////////////////////////////////////////////////
  Mercury: "mercury",
  Venus: "venus",
  Earth: "earth",
  Mars: "mars",
  Jupiter: "jupiter",
  Saturn: "saturn",
  Uranus: "uranus",
  Neptune: "neptune",
  ////////////////////////////////////////////////////
  //                 Dwarf Planets                  //
  ////////////////////////////////////////////////////
  Ceres: "1_ceres",
  Pluto: "134340_pluto",
  Haumea: "136108_haumea",
  Eris: "136199_eris",
  Makemake: "136472_makemake",
  ////////////////////////////////////////////////////
  //                    Asteroids                   //
  ////////////////////////////////////////////////////
  Bennu: "101955_bennu",
  Leucus: "11351_leucus",
  Zephyr: "12923_zephyr", // Broken
  "Pluto barycenter": "134340_pluto_barycenter", // Broken
  Hypnos: "14827_hypnos", // Broken
  Polymele: "15094_polymele",
  Icarus: "1566_icarus",
  "Psyche (asteroid)": "16_psyche",
  Geographos: "1620_geographos",
  Ryugu: "162173_ryugu",
  Apollo: "1862_apollo",
  Midas: "1981_midas",
  "1991 vg": "1991_vg",
  "1993 hd": "1993_hd",
  "1994 cc a": "1994_cc_a",
  "1996 xb27": "1996_xb27",
  "1998 ky26": "1998_ky26",
  "1998 ml14": "1998_ml14",
  "1998 qe2": "1998_qe2",
  "1999 ao10": "1999_ao10",
  "1999 cg9": "1999_cg9",
  "1999 vx25": "1999_vx25",
  Pallas: "2_pallas",
  "2000 ae205": "2000_ae205",
  "2000 lg6": "2000_lg6",
  "2000 sg344": "2000_sg344",
  "2001 bb16": "2001_bb16",
  "2001 fr85": "2001_fr85",
  "2001 gp2": "2001_gp2",
  "2001 qj142": "2001_qj142",
  "2001 sn263 a": "2001_sn263_a",
  "2003 sm84": "2003_sm84",
  "2003 uv11": "2003_uv11",
  "2003 yn107": "2003_yn107",
  "2005 er95": "2005_er95",
  "2005 lc": "2005_lc",
  "2005 qp87": "2005_qp87",
  "2005 yu55": "2005_yu55",
  "2006 bz147": "2006_bz147",
  "2006 jy26": "2006_jy26",
  "2006 qq56": "2006_qq56",
  "2006 rh120": "2006_rh120",
  "2006 ub17": "2006_ub17",
  "2007 tf15": "2007_tf15",
  "2007 un12": "2007_un12",
  "2007 vu6": "2007_vu6",
  "2008 bt2": "2008_bt2",
  "2008 cx118": "2008_cx118",
  "2008 ea9": "2008_ea9",
  "2008 el": "2008_el",
  "2008 hu4": "2008_hu4",
  "2008 jl24": "2008_jl24",
  "2008 kt": "2008_kt",
  "2008 tc3": "2008_tc3",
  "2008 ts10": "2008_ts10",
  "2008 ua202": "2008_ua202",
  "2009 bd": "2009_bd",
  "2009 os5": "2009_os5",
  "2009 rt1": "2009_rt1",
  "2009 yf": "2009_yf",
  "2010 an61": "2010_an61",
  "2010 dj": "2010_dj",
  "2010 jw34": "2010_jw34",
  "2010 tg19": "2010_tg19",
  "2010 tn167": "2010_tn167",
  "2010 ub": "2010_ub",
  Bacchus: "2063_bacchus",
  Lutetia: "21_lutetia",
  Adonis: "2101_adonis",
  Tantalus: "2102_tantalus",
  Aristaeus: "2135_aristaeus",
  Kleopatra: "216_kleopatra",
  Orus: "21900_orus",
  "2007 or10": "225088_2007_or10",
  Hathor: "2340_hathor",
  Ida: "243_ida",
  Itokawa: "25143_itokawa",
  Mathilde: "253_mathilde",
  Steins: "2867_steins",
  "3 Juno": "3_juno",
  Florence: "3122_florence",
  Phaethon: "3200_phaethon",
  Khufu: "3362_khufu",
  Eurybates: "3548_eurybates",
  Duende: "367943_duende",
  Illapa: "37655_illapa",
  Vesta: "4_vesta",
  Wilson: "4015_wilson-harrington",
  Toutatis: "4179_toutatis",
  Cuno: "4183_cuno",
  Eros: "433_eros",
  Pan: "4450_pan",
  Mithra: "4486_mithra",
  Castalia: "4769_castalia",
  Arrokoth: "486958_arrokoth",
  Ptah: "5011_ptah",
  Donaldjohanson: "52246_donaldjohanson",
  Annefrank: "5535_annefrank",
  Patroclus: "617_patroclus",
  "Patroclus barycenter": "617_patroclus_barycenter",
  Minos: "6239_minos",
  Golevka: "6489_golevka",
  Didymos: "65803_didymos",
  Moshup: "66391_moshup",
  Hermes: "69230_hermes",
  Sedna: "90377_sedna",
  Gaspra: "951_gaspra",
  Braille: "9969_braille",
  Apophis: "99942_apophis",
  Dinkinesh: "152830_dinkinesh",
  ////////////////////////////////////////////////////
  //                      Moons                     //
  ////////////////////////////////////////////////////
  // MISSING MOONS
  //  Orcus - Vanth
  //  Quaoar - Weywot
  //  Makemake - S/2015
  //  Gonggong - Xiangliu
  //  Eris - Dysnomia
  "Pluto - Charon": "charon",
  "Pluto - Hydra": "hydra",
  "Pluto - Kerberos": "kerberos",
  "Pluto - Nix": "nix",
  "Pluto - Styx": "styx",
  "Ida - Dactyl": "dactyl",
  "Didymos - Dimorphos": "dimorphos",
  "Haumea - Hiiaka": "hiiaka",
  "Haumea - Namaka": "namaka",
  "Patroclus - Menoetius": "menoetius",
  "Earth - Moon": "moon",
  "Jupiter - Adrastea": "adrastea",
  "Jupiter - Amalthea": "amalthea",
  "Jupiter - Callisto": "callisto",
  "Jupiter - Europa": "europa",
  "Jupiter - Ganymede": "ganymede",
  "Jupiter - Io": "io",
  "Jupiter - Metis": "metis",
  "Jupiter - Thebe": "thebe",
  "Jupiter - Aitne": "aitne",
  "Jupiter - Ananke": "ananke",
  "Jupiter - Aoede": "aoede",
  "Jupiter - Arche": "arche",
  "Jupiter - Autonoe": "autonoe",
  "Jupiter - Callirrhoe": "callirrhoe",
  "Jupiter - Carme": "carme",
  "Jupiter - Carpo": "carpo",
  "Jupiter - Chaldene": "chaldene",
  "Jupiter - Cyllene": "cyllene",
  "Jupiter - Dia": "dia",
  "Jupiter - Eirene": "eirene",
  "Jupiter - Elara": "elara",
  "Jupiter - Erinome": "erinome",
  "Jupiter - Ersa": "ersa",
  "Jupiter - Euanthe": "euanthe",
  "Jupiter - Eukelade": "eukelade",
  "Jupiter - Eupheme": "eupheme",
  "Jupiter - Euporie": "euporie",
  "Jupiter - Eurydome": "eurydome",
  "Jupiter - Harpalyke": "harpalyke",
  "Jupiter - Hegemone": "hegemone",
  "Jupiter - Helike": "helike",
  "Jupiter - Hermippe": "hermippe",
  "Jupiter - Herse": "herse",
  "Jupiter - Himalia": "himalia",
  "Jupiter - Iocaste": "iocaste",
  "Jupiter - Isonoe": "isonoe",
  "Jupiter - Jupiter LI": "jupiter_li",
  "Jupiter - Jupiter LII": "jupiter_lii",
  "Jupiter - Jupiter LIV": "jupiter_liv",
  "Jupiter - Jupiter LV": "jupiter_lv",
  "Jupiter - Jupiter LVI": "jupiter_lvi",
  "Jupiter - Jupiter LIX": "jupiter_lix",
  "Jupiter - Jupiter LXI": "jupiter_lxi",
  "Jupiter - Jupiter LXIII": "jupiter_lxiii",
  "Jupiter - Jupiter LXIV": "jupiter_lxiv",
  "Jupiter - Jupiter LXVI": "jupiter_lxvi",
  "Jupiter - Jupiter LXVII": "jupiter_lxvii",
  "Jupiter - Jupiter LXVIII": "jupiter_lxviii",
  "Jupiter - Jupiter LXIX": "jupiter_lxix",
  "Jupiter - Jupiter LXX": "jupiter_lxx",
  "Jupiter - Jupiter LXXII": "jupiter_lxxii",
  "Jupiter - Kale": "kale",
  "Jupiter - Kallichore": "kallichore",
  "Jupiter - Kalyke": "kalyke",
  "Jupiter - Kore": "kore",
  "Jupiter - Leda": "leda",
  "Jupiter - Lysithea": "lysithea",
  "Jupiter - Megaclite": "megaclite",
  "Jupiter - Mneme": "mneme",
  "Jupiter - Orthosie": "orthosie",
  "Jupiter - Pandia": "pandia",
  "Jupiter - Pasiphae": "pasiphae",
  "Jupiter - Pasithee": "pasithee",
  "Jupiter - Philophrosyne": "philophrosyne",
  "Jupiter - Praxidike": "praxidike",
  "Jupiter - S/2003 J 2": "s_2003_j_2",
  "Jupiter - S/2003 J 4": "s_2003_j_4",
  "Jupiter - S/2003 J 9": "s_2003_j_9",
  "Jupiter - S/2003 J 10": "s_2003_j_10",
  "Jupiter - S/2003 J 12": "s_2003_j_12",
  "Jupiter - S/2003 J 16": "s_2003_j_16",
  "Jupiter - S/2003 J 23": "s_2003_j_23",
  "Jupiter - S/2003 J 24": "s_2003_j_24",
  "Jupiter - S/2011 J 3": "s_2011_j_3",
  "Jupiter - S/2016 J 3": "s_2016_j_3",
  "Jupiter - S/2016 J 4": "s_2016_j_4",
  "Jupiter - S/2018 J 2": "s_2018_j_2",
  "Jupiter - S/2018 J 3": "s_2018_j_3",
  "Jupiter - S/2018 J 4": "s_2018_j_4",
  "Jupiter - S/2021 J 1": "s_2021_j_1",
  "Jupiter - S/2021 J 2": "s_2021_j_2",
  "Jupiter - S/2021 J 3": "s_2021_j_3",
  "Jupiter - S/2021 J 4": "s_2021_j_4",
  "Jupiter - S/2021 J 5": "s_2021_j_5",
  "Jupiter - S/2021 J 6": "s_2021_j_6",
  "Jupiter - S/2022 J 1": "s_2022_j_1",
  "Jupiter - S/2022 J 2": "s_2022_j_2",
  "Jupiter - S/2022 J 3": "s_2022_j_3",
  "Jupiter - Sinope": "sinope",
  "Jupiter - Sponde": "sponde",
  "Jupiter - Taygete": "taygete",
  "Jupiter - Thelxinoe": "thelxinoe",
  "Jupiter - THEMISto": "themisto",
  "Jupiter - Thyone": "thyone",
  "Jupiter - Valetudo": "valetudo",
  "Mars - Phobos": "phobos",
  "Mars - Deimos": "deimos",
  "Neptune - Despina": "despina",
  "Neptune - Galatea": "galatea",
  "Neptune - Halimede": "halimede",
  "Neptune - Hippocamp": "hippocamp",
  "Neptune - Laomedeia": "laomedeia",
  "Neptune - Larissa": "larissa",
  "Neptune - Naiad": "naiad",
  "Neptune - Nereid": "nereid",
  "Neptune - Neso": "neso",
  "Neptune - Proteus": "proteus",
  "Neptune - Psamathe": "psamathe",
  "Neptune - Sao": "sao",
  "Neptune - Thalassa": "thalassa",
  "Neptune - Triton": "triton",
  "Saturn - Dione": "dione",
  "Saturn - Enceladus": "enceladus",
  "Saturn - Hyperion": "hyperion",
  "Saturn - Iapetus": "iapetus",
  "Saturn - Mimas": "mimas",
  "Saturn - Rhea": "rhea",
  "Saturn - Tethys": "tethys",
  "Saturn - Titan": "titan",
  "Saturn - Aegaeon": "aegaeon",
  "Saturn - Aegir": "aegir",
  "Saturn - Albiorix": "albiorix",
  "Saturn - Alvaldi": "alvaldi",
  "Saturn - Angrboda": "angrboda",
  "Saturn - Anthe": "anthe",
  "Saturn - Atlas": "atlas",
  "Saturn - Bebhionn": "bebhionn",
  "Saturn - Beli": "beli",
  "Saturn - Bergelmir": "bergelmir",
  "Saturn - Bestla": "bestla",
  "Saturn - Calypso": "calypso",
  "Saturn - Daphnis": "daphnis",
  "Saturn - Eggther": "eggther",
  "Saturn - Epimetheus": "epimetheus",
  "Saturn - Erriapus": "erriapus",
  "Saturn - Farbauti": "farbauti",
  "Saturn - Fenrir": "fenrir",
  "Saturn - Fornjot": "fornjot",
  "Saturn - Geirrod": "geirrod",
  "Saturn - Gerd": "gerd",
  "Saturn - Greip": "greip",
  "Saturn - Gridr": "gridr",
  "Saturn - Gunnlod": "gunnlod",
  "Saturn - Hati": "hati",
  "Saturn - Helene": "helene",
  "Saturn - Hyrrokkin": "hyrrokkin",
  "Saturn - Ijiraq": "ijiraq",
  "Saturn - Janus": "janus",
  "Saturn - Jarnsaxa": "jarnsaxa",
  "Saturn - Kari": "kari",
  "Saturn - Kiviuq": "kiviuq",
  "Saturn - Loge": "loge",
  "Saturn - Methone": "methone",
  "Saturn - Mundilfari": "mundilfari",
  "Saturn - Narvi": "narvi",
  "Saturn - Paaliaq": "paaliaq",
  "Saturn - Pallene": "pallene",
  "Saturn - Pan": "pan",
  "Saturn - Pandora": "pandora",
  "Saturn - Phoebe": "phoebe",
  "Saturn - Polydeuces": "polydeuces",
  "Saturn - Prometheus": "prometheus",
  "Saturn - S/2004 S 7": "s_2004_s_7",
  "Saturn - S/2004 S 12": "s_2004_s_12",
  "Saturn - S/2004 S 13": "s_2004_s_13",
  "Saturn - S/2004 S 17": "s_2004_s_17",
  "Saturn - S/2004 S 21": "s_2004_s_21",
  "Saturn - S/2004 S 24": "s_2004_s_24",
  "Saturn - S/2004 S 28": "s_2004_s_28",
  "Saturn - S/2004 S 31": "s_2004_s_31",
  "Saturn - S/2004 S 36": "s_2004_s_36",
  "Saturn - S/2004 S 37": "s_2004_s_37",
  "Saturn - S/2004 S 39": "s_2004_s_39",
  "Saturn - S/2006 S 1": "s_2006_s_1",
  "Saturn - S/2006 S 3": "s_2006_s_3",
  "Saturn - S/2007 S 2": "s_2007_s_2",
  "Saturn - S/2007 S 3": "s_2007_s_3",
  "Saturn - S/2009 S 1": "s_2009_s_1",
  "Saturn - S/2019 S 1": "s_2019_s_1",
  "Saturn - Saturn_lviii": "saturn_lviii",
  "Saturn - Saturn_lx": "saturn_lx",
  "Saturn - Saturn_lxiv": "saturn_lxiv",
  "Saturn - Siarnaq": "siarnaq",
  "Saturn - Skathi": "skathi",
  "Saturn - Skoll": "skoll",
  "Saturn - Skrymir": "skrymir",
  "Saturn - Surtur": "surtur",
  "Saturn - Suttungr": "suttungr",
  "Saturn - Tarqeq": "tarqeq",
  "Saturn - Tarvos": "tarvos",
  "Saturn - Telesto": "telesto",
  "Saturn - Thiazzi": "thiazzi",
  "Saturn - Thrymr": "thrymr",
  "Saturn - Ymir": "ymir",
  "Saturn - S/2004 S 40": "s_2004_s_40",
  "Saturn - S/2004 S 41": "s_2004_s_41",
  "Saturn - S/2004 S 42": "s_2004_s_42",
  "Saturn - S/2004 S 43": "s_2004_s_43",
  "Saturn - S/2004 S 44": "s_2004_s_44",
  "Saturn - S/2004 S 45": "s_2004_s_45",
  "Saturn - S/2004 S 46": "s_2004_s_46",
  "Saturn - S/2004 S 47": "s_2004_s_47",
  "Saturn - S/2004 S 48": "s_2004_s_48",
  "Saturn - S/2004 S 49": "s_2004_s_49",
  "Saturn - S/2004 S 50": "s_2004_s_50",
  "Saturn - S/2004 S 51": "s_2004_s_51",
  "Saturn - S/2004 S 52": "s_2004_s_52",
  "Saturn - S/2004 S 53": "s_2004_s_53",
  "Saturn - S/2005 S 4": "s_2005_s_4",
  "Saturn - S/2005 S 5": "s_2005_s_5",
  "Saturn - S/2006 S 10": "s_2006_s_10",
  "Saturn - S/2006 S 11": "s_2006_s_11",
  "Saturn - S/2006 S 12": "s_2006_s_12",
  "Saturn - S/2006 S 13": "s_2006_s_13",
  "Saturn - S/2006 S 14": "s_2006_s_14",
  "Saturn - S/2006 S 15": "s_2006_s_15",
  "Saturn - S/2006 S 16": "s_2006_s_16",
  "Saturn - S/2006 S 17": "s_2006_s_17",
  "Saturn - S/2006 S 18": "s_2006_s_18",
  "Saturn - S/2006 S 19": "s_2006_s_19",
  "Saturn - S/2006 S 20": "s_2006_s_20",
  "Saturn - S/2006 S 9": "s_2006_s_9",
  "Saturn - S/2007 S 5": "s_2007_s_5",
  "Saturn - S/2007 S 6": "s_2007_s_6",
  "Saturn - S/2007 S 7": "s_2007_s_7",
  "Saturn - S/2007 S 8": "s_2007_s_8",
  "Saturn - S/2007 S 9": "s_2007_s_9",
  "Saturn - S/2019 S 10": "s_2019_s_10",
  "Saturn - S/2019 S 11": "s_2019_s_11",
  "Saturn - S/2019 S 12": "s_2019_s_12",
  "Saturn - S/2019 S 13": "s_2019_s_13",
  "Saturn - S/2019 S 14": "s_2019_s_14",
  "Saturn - S/2019 S 15": "s_2019_s_15",
  "Saturn - S/2019 S 16": "s_2019_s_16",
  "Saturn - S/2019 S 17": "s_2019_s_17",
  "Saturn - S/2019 S 18": "s_2019_s_18",
  "Saturn - S/2019 S 19": "s_2019_s_19",
  "Saturn - S/2019 S 2": "s_2019_s_2",
  "Saturn - S/2019 S 20": "s_2019_s_20",
  "Saturn - S/2019 S 21": "s_2019_s_21",
  "Saturn - S/2019 S 3": "s_2019_s_3",
  "Saturn - S/2019 S 4": "s_2019_s_4",
  "Saturn - S/2019 S 5": "s_2019_s_5",
  "Saturn - S/2019 S 6": "s_2019_s_6",
  "Saturn - S/2019 S 7": "s_2019_s_7",
  "Saturn - S/2019 S 8": "s_2019_s_8",
  "Saturn - S/2019 S 9": "s_2019_s_9",
  "Saturn - S/2020 S 1": "s_2020_s_1",
  "Saturn - S/2020 S 10": "s_2020_s_10",
  "Saturn - S/2020 S 2": "s_2020_s_2",
  "Saturn - S/2020 S 3": "s_2020_s_3",
  "Saturn - S/2020 S 4": "s_2020_s_4",
  "Saturn - S/2020 S 5": "s_2020_s_5",
  "Saturn - S/2020 S 6": "s_2020_s_6",
  "Saturn - S/2020 S 7": "s_2020_s_7",
  "Saturn - S/2020 S 8": "s_2020_s_8",
  "Saturn - S/2020 S 9": "s_2020_s_9",
  "Uranus - Ariel": "ariel",
  "Uranus - Miranda": "miranda",
  "Uranus - Oberon": "oberon",
  "Uranus - Titania": "titania",
  "Uranus - Umbriel": "umbriel",
  "Uranus - Belinda": "belinda",
  "Uranus - Bianca": "bianca",
  "Uranus - Caliban": "caliban",
  "Uranus - Cordelia": "cordelia",
  "Uranus - Cressida": "cressida",
  "Uranus - Cupid": "cupid",
  "Uranus - Desdemona": "desdemona",
  "Uranus - Ferdinand": "ferdinand",
  "Uranus - Francisco": "francisco",
  "Uranus - Juliet": "juliet",
  "Uranus - Mab": "mab",
  "Uranus - Margaret": "margaret",
  "Uranus - Ophelia": "ophelia",
  "Uranus - Perdita": "perdita",
  "Uranus - Portia": "portia",
  "Uranus - Prospero": "prospero",
  "Uranus - Puck": "puck",
  "Uranus - Rosalind": "rosalind",
  "Uranus - Setebos": "setebos",
  "Uranus - Stephano": "stephano",
  "Uranus - Sycorax": "sycorax",
  "Uranus - Trinculo": "trinculo",
  ////////////////////////////////////////////////////
  //                     Comets                     //
  ////////////////////////////////////////////////////
  Oumuamua: "1i_oumuamua",
  Halley: "1p_halley",
  "Hartley 2": "103p_hartley_2",
  "Tempel 1": "9p_tempel_1",
  "Wild 2": "81p_wild_2",
  "Churyumov Gerasimenko": "67p_churyumov_gerasimenko",
  Borrelly: "19p_borrelly",
  "C 1995 o1": "c_1995_o1",
  "C 2010 x1": "c_2010_x1",
  "C 2012 s1": "c_2012_s1",
  "C 2013 a1": "c_2013_a1",
  "C 2019 y4": "c_2019_y4",
  "C 2020 f3": "c_2020_f3",
  ////////////////////////////////////////////////////
  //                   Spacecraft                   //
  ////////////////////////////////////////////////////
  "3d winds": "sc_3d_winds",
  Ace: "sc_ace",
  Acrimsat: "sc_acrimsat",
  Aim: "sc_aim",
  Aqua: "sc_aqua",
  Ascends: "sc_ascends",
  Aura: "sc_aura",
  "C nofs": "sc_c_nofs",
  CALIPSO: "sc_calipso",
  "Chandra X-ray Observatory": "sc_chandra",
  Clarreo: "sc_clarreo",
  CloudSat: "sc_cloudsat",
  "Rumba": "sc_cluster_ii_fm5",
  "Salsa": "sc_cluster_ii_fm6",
  "Samba": "sc_cluster_ii_fm7",
  "Tango": "sc_cluster_ii_fm8",
  "Cygnss 1": "sc_cygnss_1",
  "Cygnss 2": "sc_cygnss_2",
  "Cygnss 3": "sc_cygnss_3",
  "Cygnss 4": "sc_cygnss_4",
  "Cygnss 5": "sc_cygnss_5",
  "Cygnss 6": "sc_cygnss_6",
  "Cygnss 7": "sc_cygnss_7",
  "Cygnss 8": "sc_cygnss_8",
  Dscovr: "sc_dscovr",
  "EO-1": "sc_eo_1",
  "Explorer 1": "sc_explorer_1",
  Face: "sc_face",
  Fgrst: "sc_fgrst",
  Gacm: "sc_gacm",
  Galex: "sc_galex",
  "Geo cape": "sc_geo_cape",
  Geotail: "sc_geotail",
  "Goes 12": "sc_goes_12",
  "Goes 13": "sc_goes_13",
  "Goes 14": "sc_goes_14",
  "Goes 15": "sc_goes_15",
  Gpm: "sc_gpm",
  "GRACE-1": "sc_grace_1",
  "GRACE-2": "sc_grace_2",
  "GRACE-FO1": "sc_grace_fo1",
  "GRACE-FO2": "sc_grace_fo2",
  Grifex: "sc_grifex",
  "Hubble Space Telescope": "sc_hubble_space_telescope",
  Hyspiri: "sc_hyspiri",
  Ibex: "sc_ibex",
  Icesat_2: "sc_icesat_2",
  Image: "sc_image",
  Integral: "sc_integral",
  Ipex: "sc_ipex",
  Isas: "sc_isas",
  "International Space Station (ISS)": "sc_iss",
  IXPE: "sc_ixpe", // Broken
  "Jason-1": "sc_jason_1", // Broken
  "Jason-2": "sc_jason_2", // Broken
  "Jason-3": "sc_jason_3", // Broken
  "James Webb Space Telescope": "sc_jwst", // Broken
  "Landsat 5": "sc_landsat_5", // Broken
  "Landsat 7": "sc_landsat_7", // Broken
  "Landsat 8": "sc_landsat_8", // Broken
  "Landsat 9": "sc_landsat_9", // Broken
  "M cubed": "sc_m_cubed", // Broken
  "M cubed 2": "sc_mcubed_2", // Broken
  "MMS 1": "sc_mms_1", // Broken
  "MMS 2": "sc_mms_2", // Broken
  "MMS 3": "sc_mms_3", // Broken
  "MMS 4": "sc_mms_4", // Broken
  Nisar: "sc_nisar", // Broken
  "Noaa 14": "sc_noaa_14", // Broken
  "Noaa 15": "sc_noaa_15", // Broken
  "Noaa 16": "sc_noaa_16", // Broken
  "Noaa 17": "sc_noaa_17", // Broken
  "Noaa 18": "sc_noaa_18", // Broken
  "Noaa 19": "sc_noaa_19", // Broken
  Nustar: "sc_nustar", // Broken
  "OCO-2": "sc_oco_2", // Broken
  Path: "sc_path", // Broken
  Polar: "sc_polar", // Broken
  QuikSCAT: "sc_quikscat", // Broken
  Race: "sc_race", // Broken
  Raincube: "sc_raincube", // Broken
  "Rax 2": "sc_rax_2", // Broken
  "Van Allen Probe A": "sc_rbsp_a", // Broken
  "Van Allen Probe B": "sc_rbsp_b", // Broken
  "Sac d": "sc_sac_d", // Broken
  Sclp: "sc_sclp", // Broken
  Sdo: "sc_sdo", // Broken
  "Sentinel-6 Michael Freilich": "sc_sentinel_6", // Broken
  Smap: "sc_smap", // Broken
  Soho: "sc_soho", // Broken
  Sorce: "sc_sorce", // Broken
  "Starling 1": "sc_starling_1", // Broken
  "Starling 2": "sc_starling_2", // Broken
  "Starling 3": "sc_starling_3", // Broken
  "Starling 4": "sc_starling_4", // Broken
  Suomi_npp: "sc_suomi_npp", // Broken
  Swift: "sc_swift", // Broken
  Swot: "sc_swot", // Broken
  "Tdrs 3": "sc_tdrs_3", // Broken
  "Tdrs 5": "sc_tdrs_5", // Broken
  "Tdrs 6": "sc_tdrs_6", // Broken
  "Tdrs 7": "sc_tdrs_7", // Broken
  "Tdrs 8": "sc_tdrs_8", // Broken
  "Tdrs 9": "sc_tdrs_9", // Broken
  "Tdrs 10": "sc_tdrs_10", // Broken
  "Tdrs 11": "sc_tdrs_11", // Broken
  "Tdrs 12": "sc_tdrs_12", // Broken
  "Tdrs 13": "sc_tdrs_13", // Broken
  Terra: "sc_terra", // Broken
  Tess: "sc_tess", // Broken
  "THEMIS a": "sc_themis_a",
  "THEMIS d": "sc_themis_d",
  "THEMIS e": "sc_themis_e",
  Timed: "sc_timed",
  Trmm: "sc_trmm",
  Uars: "sc_uars",
  WIND: "sc_wind",
  Wise: "sc_wise",
  "Apollo 15": "sc_apollo_15",
  "Artemis 1": "sc_artemis_1",
  CAPSTONE: "sc_capstone",
  Clementine: "sc_clementine",
  "GRAIL A": "sc_grail_a",
  "GRAIL B": "sc_grail_b",
  Ladee: "sc_ladee",
  LCROSS: "sc_lcross",
  "LCROSS impact site": "sc_lcross_impact_site",
  "Lunar flashlight": "sc_lunar_flashlight",
  "Lunar Prospector": "sc_lunar_prospector",
  "Lunar reconnaissance_orbiter": "sc_lunar_reconnaissance_orbiter",
  "Smart 1": "sc_smart_1",
  "ARTEMIS P1": "sc_themis_b",
  "ARTEMIS P2": "sc_themis_c",
  "Mars 2020": "sc_mars_2020",
  "Mars 2020 landing site": "sc_mars_2020_landing_site",
  "Mars science laboratory": "sc_mars_science_laboratory", // Broken
  "Mars science laboratory_landing_site":
    "sc_mars_science_laboratory_landing_site", // Broken
  Insight: "sc_insight", // Broken
  "Insight landing site": "sc_insight_landing_site", // Broken
  "MarCO A": "sc_marco_a", // Broken
  "MarCO B": "sc_marco_b", // Broken
  "Mars odyssey": "sc_mars_odyssey", // Broken
  "Mars reconnaissance orbiter": "sc_mars_reconnaissance_orbiter", // Broken
  Maven: "sc_maven", // Broken
  "Mars express": "sc_mars_express", // Broken
  Phoenix: "sc_phoenix", // Broken
  "Phoenix landing site": "sc_phoenix_landing_site", // Broken
  "Trace gas orbiter": "sc_trace_gas_orbiter", // Broken
  "Mars orbiter mission": "sc_mars_orbiter_mission", // Broken
  "Mars Global Surveyor": "sc_mars_global_surveyor", // Broken
  "Mars climate orbiter": "sc_mars_climate_orbiter", // Broken
  "Mars pathfinder": "sc_mars_pathfinder", // Broken
  "Mars pathfinder landing site": "sc_mars_pathfinder_landing_site", // Broken
  "Mars polar lander": "sc_mars_polar_lander", // Broken
  "Viking 2 orbiter": "sc_viking_2_orbiter", // Broken
  "Viking 2 lander landing site": "sc_viking_2_lander_landing_site", // Broken
  MESSENGER: "sc_messenger", // Broken
  "MESSENGER impact site": "sc_messenger_impact_site", // Broken
  Juno: "sc_juno", // Broken
  Cassini: "sc_cassini", // Broken
  "Europa clipper": "sc_europa_clipper", // Broken
  Galileo: "sc_galileo",
  "Galileo probe": "sc_galileo_probe", // Broken
  Huygens: "sc_huygens",
  "Huygens landing site": "sc_huygens_landing_site", // Broken
  Juice: "sc_juice", // Broken
  "Pioneer 10": "sc_pioneer_10", // Broken
  "Pioneer 11": "sc_pioneer_11", // Broken
  "Voyager 1": "sc_voyager_1", // Broken
  "Voyager 2": "sc_voyager_2", // Broken
  DART: "sc_dart",
  Dawn: "sc_dawn",
  "Deep Impact": "sc_deep_impact",
  "Deep Impact Impactor": "sc_deep_impact_impactor",
  "Deep impact_impactor_impact_site": "sc_deep_impact_impactor_impact_site", // Broken
  "Deep Space 1": "sc_deep_space_1",
  "NEAR Shoemaker": "sc_near_shoemaker",
  "NEAR Shoemaker_landing_site": "sc_near_shoemaker_landing_site", // Broken
  Lucy: "sc_lucy", // VERY Broken
  "New Horizons": "sc_new_horizons", // Broken
  Rosetta: "sc_rosetta",
  "Rosetta impact site": "sc_rosetta_impact_site", // Broken
  "OSIRIS-APEX (OSIRIS-REx)": "sc_osiris_rex",
  "OSIRIS-REx Sample Return Capsule": "sc_osiris_rex_src",
  Philae: "sc_philae",
  Philae_landing_site: "sc_philae_landing_site", // Broken
  "Psyche (spacecraft)": "sc_psyche",
  "Stardust": "sc_stardust",
  BioSentinel: "sc_biosentinel", // Broken
  "Kepler": "sc_kepler_space_telescope",
  "Mariner 2": "sc_mariner_2", // Broken
  "Parker Solar Probe": "sc_parker_solar_probe", // Broken
  "Spitzer Space Telescope": "sc_spitzer", // Broken
  "STEREO ahead": "sc_stereo_ahead", // Broken
  "STEREO behind": "sc_stereo_behind", // Broken
  Ulysses: "sc_ulysses", // Broken
  Wmap: "sc_wmap", // Broken
  Magellan: "sc_magellan", // Broken
  "Venus express": "sc_venus_express", // Broken
  ////////////////////////////////////////////////////
  //                     Unused                     //
  ////////////////////////////////////////////////////
  // "rose_bowl",
  // "school_bus",
  // "scientist"
};
