/* Book of Mormon translations, 1830-2024.
 *
 * A passive wall piece: it cycles language pages, each showing the book's
 * title and a verse set in that language's own script plus where the language
 * is spoken, and every few pages it steps back to an atlas that plays the
 * whole timeline out across the map.
 *
 * Everything is drawn from data/vector sources at runtime -- no photographs.
 * data.json and world.json are generated by tools/build_all.sh; see the
 * scripts there for provenance (Wikipedia for the translation table, Natural
 * Earth for the geometry, the Church's own scripture text for the verses).
 */
'use strict';

/* ------------------------------------------------------------------ tuning */
/* These are the knobs worth touching. SCOPE decides how many languages get
 * their own page: 'curated' plays the FEATURED list below, 'all' plays every
 * translation in the file (~126 pages, a ~23 minute cycle). */
const SCOPE       = 'curated';
const PAGE_MS     = 11000;   // dwell per language page
const ATLAS_MS    = 17000;   // dwell on the timeline atlas
const ATLAS_EVERY = 6;       // atlas interlude after this many language pages
const FADE_MS     = 900;     // must match the .scene transition in the CSS

/* Chosen for spread rather than fame: every inhabited continent, ten writing
 * systems, and the gaps that tell the story (nothing 1910-1932, a flood after
 * 2000). Reorder or trim freely -- unknown names are simply skipped. */
const FEATURED = [
  'English', 'Danish', 'Welsh', 'Hawaiian', 'Deseret Alphabet (English)',
  'Spanish', 'Māori', 'Samoan', 'Japanese', 'Czech', 'Tongan',
  'Chinese', 'Korean', 'Afrikaans', 'Thai', "Q'eqchi' (Kekchi)", 'Arabic',
  'Hungarian', 'Cebuano', 'Haitian Creole', 'Amharic',
  'Khmer (Cambodian)', 'Zulu', 'Tamil', 'Georgian', 'Kinyarwanda', 'Maltese',
];

/* The sequential ramp: one hue, oldest -> newest. On a dark ground it runs
 * dim -> bright rather than light -> dark, so that "newer" still means "more
 * contrast against the surface" and the ramp reads the same way round. Every
 * step stays clear of --land (#4e463a), or an early translation would be
 * indistinguishable from a country with none. */
const ERAS = [
  { from: 1830, to: 1889, fill: '#8a6a33' },
  { from: 1890, to: 1949, fill: '#a67f3c' },
  { from: 1950, to: 1979, fill: '#c29648' },
  { from: 1980, to: 1999, fill: '#dcb05e' },
  { from: 2000, to: 2100, fill: '#f7d48c' },
];
const eraFill = (y) => (ERAS.find((e) => y >= e.from && y <= e.to) || ERAS[0]).fill;

const SVG = 'http://www.w3.org/2000/svg';
const el = (tag, attrs) => {
  const n = document.createElementNS(SVG, tag);
  for (const k in attrs) if (attrs[k] != null) n.setAttribute(k, attrs[k]);
  return n;
};
const div = (cls, html) => {
  const n = document.createElement('div');
  if (cls) n.className = cls;
  if (html != null) n.innerHTML = html;
  return n;
};
/* Speaker counts arrive as free text: "5,500,000", "400,000,000 / as a
   foreign language: 600-700,000,000", "NA", "unknown". Keep the first figure
   and only when there is actually a figure. */
const speakerCount = (s) => {
  const head = (s || '').split('/')[0].trim();
  return /\d/.test(head) ? head : '';
};

/* The locations column ranges from "Peru" to a full paragraph on dialects.
   Column three already names the places, so here we only want a glance --
   cut at the first sentence and then, if still long, at a word boundary. */
const shortPlaces = (s) => {
  let t = (s || '').split(/\.\s/)[0].trim();
  if (t.length > 72) t = t.slice(0, 72).replace(/[\s,;]+\S*$/, '') + '…';
  return t;
};

/* Wikipedia often appends a romanisation -- "モルモン書 (Morumon-sho)". A real
   cover carries only the title, so drop a trailing ASCII-only parenthetical
   for the stamp (the full string stays in the data). */
const coverTitle = (t) => (t || '').replace(/\s*\(\s*[\x20-\x7E]+\s*\)\s*$/, '').trim() || t;

/* ------------------------------------------------------------- text fitting */
/* Shrink until it fits. The box must have its own height from the layout --
 * a box sized by its contents measures as whatever the last fit left behind,
 * so each pass would ratchet the type down a little further. */
function fitText(node, maxEm, minEm) {
  const box = node.parentElement;
  let lo = minEm, hi = maxEm;
  for (let i = 0; i < 7; i++) {
    const mid = (lo + hi) / 2;
    node.style.fontSize = mid + 'em';
    const fits = node.scrollHeight <= box.clientHeight &&
                 node.scrollWidth  <= box.clientWidth + 1;
    if (fits) lo = mid; else hi = mid;
  }
  node.style.fontSize = lo + 'em';
}

/* ---------------------------------------------------------------- the maps */
/* `suf` selects the projection: '' is Atlantic-centred, 'Pac' is centred on
   150E. Both are baked into world.json by tools/build_geo.py. */
function lookupGeo(world, g, suf) {
  /* -> { paths: [d...], pins: [[x,y]...] } for one resolved location */
  const countries = world['countries' + (suf || '')];
  const points = world['points' + (suf || '')];
  const out = { paths: [], pins: [] };
  if (g.kind === 'country') {
    const c = countries[g.key];
    if (c) { out.paths.push(c.d); out.pins.push(c.c); }
  } else if (g.kind === 'point') {
    const p = points[g.key];
    if (p) out.pins.push(p.c);
  } else if (g.kind === 'region') {
    for (const iso of g.isos || []) {
      const c = countries[iso];
      if (c) out.paths.push(c.d);
    }
  }
  return out;
}

/* Where the language actually lives. Entries flagged `secondary` by
   tools/build_geo.py are places the source mentions only as a minority or
   diaspora -- lighting those would paint the whole United States for
   Hawaiian, or all of Central Asia for Kazakh. */
const primaryGeo = (rec) => (rec.geo || []).filter((g) => !g.secondary);

/* Pick the projection that holds this language's places together. A Pacific
   language is torn across both edges of an Atlantic-centred map (Fiji at 98%,
   Tonga at 3%), so the variant with the narrower spread is the right one --
   no hardcoded longitudes needed. */
function pickProjection(world, rec) {
  const W = world.viewBox[2];
  let best = '', bestScore = Infinity;
  for (const suf of ['', 'Pac']) {
    const pins = primaryGeo(rec).flatMap((g) => lookupGeo(world, g, suf).pins);
    if (!pins.length) continue;
    const xs = pins.map((p) => p[0]);
    const spread = Math.max(...xs) - Math.min(...xs);
    /* Distance from the nearest left/right edge. Spread alone cannot decide a
       single-location language -- Tonga is one pin either way -- but Tonga
       sits 3% from the Atlantic map's edge and 59% across the Pacific one,
       and only the second can show it in the middle of its own ocean. */
    const edge = Math.min(...pins.map((p) => Math.min(p[0], W - p[0])));
    const score = spread - edge;
    if (score < bestScore) { best = suf; bestScore = score; }
  }
  return best;
}

/* A world map cropped toward the lit region. Full-world context on a 30%-wide
 * column makes Tonga a sub-pixel dot; cropping all the way to Tonga loses the
 * "where on earth is that" the map exists to answer. So: crop to the lit
 * features, then force the window back open to at least MIN_W of the world. */
/* Width:height the crop is built to, matching the shape of the map column so
   the SVG does not letterbox inside its box. */
const MAP_ASPECT = 1.15;

function miniMap(world, rec) {
  const [, , W, H] = world.viewBox;
  const suf = pickProjection(world, rec);
  const countries = world['countries' + suf];
  /* The boundary shape is the projection's own edge, identical whichever
     meridian we centre on, so world.json ships it once. */
  const outline = world.outline;
  const lit = primaryGeo(rec).map((g) => lookupGeo(world, g, suf));
  const pins = lit.flatMap((l) => l.pins);
  const litPaths = lit.flatMap((l) => l.paths);

  let vb = [0, 0, W, H];
  if (pins.length) {
    let x0 = Math.min(...pins.map((p) => p[0])), x1 = Math.max(...pins.map((p) => p[0]));
    let y0 = Math.min(...pins.map((p) => p[1])), y1 = Math.max(...pins.map((p) => p[1]));
    const padX = Math.max((x1 - x0) * 0.55, W * 0.10);
    const padY = Math.max((y1 - y0) * 0.55, H * 0.10);
    x0 -= padX; x1 += padX; y0 -= padY; y1 += padY;

    /* Open the crop until enough other countries are in frame to recognise
       where we are. A fixed minimum width cannot do this job: 26% of the
       world around Cambodia is most of Asia, while 26% around Tonga is bare
       ocean, and a map of bare ocean answers nothing. */
    const CONTEXT = 7;
    const centroids = Object.keys(countries).map((iso) => countries[iso].c);
    let w = Math.max(x1 - x0, W * 0.16), h, cx, cy;
    for (let guard = 0; guard < 24; guard++) {
      h = Math.max(w / MAP_ASPECT, y1 - y0);
      w = Math.max(w, h * MAP_ASPECT);
      cx = Math.min(Math.max((x0 + x1) / 2, w / 2), W - w / 2);
      cy = Math.min(Math.max((y0 + y1) / 2, h / 2), H - h / 2);
      const inFrame = centroids.filter((c) =>
        c[0] > cx - w / 2 && c[0] < cx + w / 2 &&
        c[1] > cy - h / 2 && c[1] < cy + h / 2).length;
      if (inFrame >= CONTEXT || w >= W) break;
      w = Math.min(w * 1.22, W);
    }
    vb = [cx - w / 2, cy - h / 2, w, h];
  }

  const svg = el('svg', { viewBox: vb.join(' '), 'aria-hidden': 'true' });
  svg.appendChild(el('path', { class: 'm-outline', d: outline }));
  const litSet = new Set(litPaths);
  for (const iso in countries) {
    const c = countries[iso];
    svg.appendChild(el('path', { class: litSet.has(c.d) ? 'c-lit' : 'c-land', d: c.d }));
  }
  /* Pins scale with the crop so they stay the same size on screen. The lit
     country can be a few pixels across (Tonga, Malta), so the pin - not the
     fill - is what actually answers "where". */
  const r = vb[2] / 90;
  for (const [x, y] of pins) {
    svg.appendChild(el('circle', { class: 'pin-halo', cx: x, cy: y, r: r * 2.6 }));
    svg.appendChild(el('circle', { class: 'pin-dot',  cx: x, cy: y, r: r }));
  }
  return svg;
}

/* --------------------------------------------------------- timeline ribbon */
function ribbon(all, current) {
  const Y0 = 1830, Y1 = 2025, W = 1000, H = 72;
  const x = (y) => ((y - Y0) / (Y1 - Y0)) * W;
  const svg = el('svg', { viewBox: `0 0 ${W} ${H}`, preserveAspectRatio: 'none' });

  svg.appendChild(el('line', { class: 't-axis', x1: 0, y1: H - 22, x2: W, y2: H - 22 }));
  for (let y = 1850; y <= 2020; y += 10) {
    const major = y % 50 === 0;
    svg.appendChild(el('line', {
      class: 't-decade', x1: x(y), y1: H - 22, x2: x(y), y2: H - (major ? 12 : 17),
    }));
    if (major) {
      const t = el('text', { class: 't-label', x: x(y), y: H - 1, 'text-anchor': 'middle' });
      t.textContent = y;
      svg.appendChild(t);
    }
  }
  for (const rec of all) {
    if (!rec.year) continue;
    const isNow = current && rec.language === current.language;
    svg.appendChild(el('line', {
      class: isNow ? 't-now' : 't-tick',
      x1: x(rec.year), y1: H - 22, x2: x(rec.year), y2: isNow ? 6 : 30,
      stroke: isNow ? null : eraFill(rec.year),
      opacity: isNow ? 1 : 0.55,
    }));
  }
  return svg;
}

/* ------------------------------------------------------------ language page */
function languageScene(world, all, rec) {
  const scene = div('scene lang');

  const ghost = div('yearGhost');
  ghost.textContent = rec.year || '';
  scene.appendChild(ghost);

  /* -- the book ------------------------------------------------------- */
  const wrap = div('bookWrap');
  const book = div('book');
  const title = div('bookTitle');
  title.textContent = coverTitle(rec.nativeTitle) || rec.language;
  title.style.fontFamily = `"${rec.font}", "Noto Serif", serif`;
  if (rec.rtl) title.setAttribute('dir', 'rtl');
  if (rec.langCode) title.setAttribute('lang', rec.langCode);
  if ((rec.scripts || []).includes('DESERET')) title.classList.add('wide');
  book.appendChild(title);
  const foot = div('bookFoot');
  foot.textContent = rec.language;
  book.appendChild(foot);
  wrap.appendChild(book);
  scene.appendChild(wrap);

  /* -- the words ------------------------------------------------------ */
  const words = div('words');
  const ord = all.filter((r) => r.year && rec.year && r.year < rec.year).length + 1;
  const kicker = div('kicker');
  kicker.appendChild(div('ord', statusLabel(rec)));
  kicker.appendChild(div(null, `${ord}${ordSuffix(ord)} language`));
  words.appendChild(kicker);

  const head = div('langName');
  head.textContent = rec.language;
  words.appendChild(head);
  const yr = div('langYear');
  yr.textContent = rec.year || '';
  words.appendChild(yr);

  const meta = div('langMeta');
  const bits = [];
  const speakers = speakerCount(rec.speakers);
  if (speakers) bits.push(`<b>${speakers}</b> speakers`);
  const places = shortPlaces(rec.locationsText);
  if (places) bits.push(places);
  meta.innerHTML = bits.join(' &middot; ');
  words.appendChild(meta);

  if (rec.verse) {
    const holder = div('verseHolder');
    holder.style.cssText = 'flex:1 1 auto;min-height:0;display:flex;flex-direction:column;justify-content:center';
    const v = div('verse');
    v.textContent = rec.verse;
    v.style.fontFamily = `"${rec.verseFont || rec.font}", "Noto Serif", serif`;
    if (rec.rtl) v.setAttribute('dir', 'rtl');
    if (rec.verseLang) v.setAttribute('lang', rec.verseLang);
    holder.appendChild(v);
    const ref = div('verseRef');
    /* verseRef is the chapter title in that language ("1 Nephi 3",
       "モロナイ書10"), so the verse number is appended here. */
    ref.textContent = rec.verseRef ? rec.verseRef + ':7' : '1 Nephi 3:7';
    holder.appendChild(ref);
    words.appendChild(holder);
    scene._fit = () => fitText(v, 1.75, 0.72);
  } else {
    /* Braille, sign language and the out-of-print editions have no text to
       set -- say why rather than leaving a hole in the layout. */
    const none = div('verseNone');
    none.textContent = verseExcuse(rec);
    words.appendChild(none);
  }
  scene.appendChild(words);

  /* -- the place ------------------------------------------------------ */
  const place = div('place');
  if (primaryGeo(rec).length) {
    place.appendChild(div('placeLabel', 'Where it is spoken'));
    const box = div('mapBox');
    box.appendChild(miniMap(world, rec));
    place.appendChild(box);
    const names = primaryGeo(rec)
      .map((g) => g.kind === 'country' ? (world.countries[g.key] || {}).n
                : g.kind === 'point'   ? (world.points[g.key] || {}).n
                : g.key)
      .filter(Boolean).slice(0, 5);
    place.appendChild(div('placeNames', names.join(' &middot; ')));
  }
  scene.appendChild(place);

  const rib = div('ribbon');
  rib.appendChild(ribbon(all, rec));
  scene.appendChild(rib);

  /* The book title is fitted after the scene is in the document, because it
     needs a real measured box. Queued for the caller to run on mount. */
  const fitVerse = scene._fit;
  scene._fit = () => {
    fitText(title, (rec.scripts || []).includes('DESERET') ? 1.9 : 2.7, 0.8);
    if (fitVerse) fitVerse();
  };
  return scene;
}

const ordSuffix = (n) =>
  (n % 100 >= 11 && n % 100 <= 13) ? 'th' : ['th', 'st', 'nd', 'rd'][n % 10] || 'th';

function statusLabel(rec) {
  if (rec.status === 'selections') return 'Selections';
  if (rec.status === 'in-progress') return 'In progress';
  if (rec.status === 'out-of-print') return 'Out of print';
  return 'Complete edition';
}

function verseExcuse(rec) {
  const l = rec.language || '';
  if (l.indexOf('Braille') === 0) return 'Published in Braille — a page of it cannot be shown in ink.';
  if (l.indexOf('American Sign') === 0) return 'Published as video in American Sign Language, which has no written form to set here.';
  if (rec.status === 'out-of-print') return 'This edition is out of print, and its text is not published online.';
  return 'No online text is available for this edition.';
}

/* ------------------------------------------------------------- atlas scene */
function atlasScene(world, all) {
  const scene = div('scene atlas');
  const dated = all.filter((r) => r.year && primaryGeo(r).length);

  const head = div('atlasHead');
  const left = div();
  left.appendChild(div('atlasTitle', 'One book, 100+ languages'));
  left.appendChild(div('atlasSub',
    'Every published translation of the Book of Mormon, in the year it first appeared — ' +
    'from Joseph Smith’s English in 1830 to Maltese, Swati and Tshilubà in 2024. ' +
    'Each country is shaded for the first language spoken there to be published.'));
  const right = div();
  const bigYear = div('atlasYear');
  const count = div('atlasCount');
  right.appendChild(bigYear);
  right.appendChild(count);
  head.appendChild(left);
  head.appendChild(right);
  scene.appendChild(head);

  /* One <path> per country, recoloured as the years sweep past. */
  const [, , W, H] = world.viewBox;
  const svg = el('svg', { viewBox: `0 0 ${W} ${H}` });
  svg.appendChild(el('path', { class: 'm-outline', d: world.outline }));
  const nodes = {};
  for (const iso in world.countries) {
    const p = el('path', { class: 'c-land', d: world.countries[iso].d });
    nodes[iso] = p;
    svg.appendChild(p);
  }
  const pinLayer = el('g', {});
  svg.appendChild(pinLayer);
  const mapBox = div('atlasMap');
  mapBox.appendChild(svg);
  scene.appendChild(mapBox);

  const foot = div('atlasHead');
  const legend = div('legend');
  legend.appendChild(div(null, '1830'));
  const ramp = div('legendRamp');
  for (const e of ERAS) {
    const i = document.createElement('i');
    i.style.background = e.fill;
    ramp.appendChild(i);
  }
  legend.appendChild(ramp);
  legend.appendChild(div(null, '2024'));
  foot.appendChild(legend);
  const src = div('atlasCount', 'Wikipedia · Natural Earth · scriptures of the Church');
  foot.appendChild(src);
  scene.appendChild(foot);

  /* The state of the map at one year, as a pure function of that year.
     Keeping it pure rather than accumulating inside the animation loop means
     the same code renders a frozen frame (?year=1980) and the sweep, and one
     can be checked without waiting on the other. */
  const order = dated.slice().sort((a, b) => a.year - b.year);
  const Y0 = 1830, Y1 = 2024;

  const paintTo = (year) => {
    bigYear.textContent = year;
    for (const iso in nodes) {
      nodes[iso].setAttribute('class', 'c-land');
      nodes[iso].removeAttribute('style');
    }
    while (pinLayer.firstChild) pinLayer.removeChild(pinLayer.firstChild);

    /* `order` runs oldest first and a country keeps the colour of the FIRST
       language to reach it. Letting later ones overwrite would make the ramp
       show whichever translation happened to come last, which is not a date
       anyone can read anything from. */
    const taken = new Set();
    const paint = (iso, fill, opacity) => {
      if (taken.has(iso) || !nodes[iso]) return;
      taken.add(iso);
      nodes[iso].setAttribute('class', '');
      nodes[iso].setAttribute('style',
        `fill:${fill};stroke:var(--map-stroke);stroke-width:.4;stroke-opacity:.5` +
        (opacity < 1 ? `;fill-opacity:${opacity}` : ''));
    };

    let n = 0;
    for (const rec of order) {
      if (rec.year > year) break;
      n++;
      const fill = eraFill(rec.year);
      for (const g of primaryGeo(rec)) {
        if (g.kind === 'country') {
          paint(g.key, fill, 1);
        } else if (g.kind === 'region') {
          /* A region says where a language is spoken, not that each of those
             countries published an edition, so it sits lighter. */
          for (const iso of g.isos || []) paint(iso, fill, 0.55);
        } else if (g.kind === 'point') {
          for (const [px, py] of lookupGeo(world, g).pins) {
            pinLayer.appendChild(el('circle', {
              cx: px, cy: py, r: W / 320,
              style: `fill:${fill};stroke:var(--surface);stroke-width:.5`,
            }));
          }
        }
      }
    }
    count.textContent = `${n} translation${n === 1 ? '' : 's'}`;
  };

  scene._paintTo = paintTo;
  paintTo(Y0);

  /* The sweep, repainting only when the year actually ticks over -- at most
     195 repaints across the whole run rather than one per frame. */
  scene._play = () => {
    const start = performance.now();
    let shown = -1;
    const step = (now) => {
      if (!scene.isConnected || !scene.classList.contains('live')) return;
      const t = Math.min(1, (now - start) / (ATLAS_MS - FADE_MS - 1200));
      /* ease-out so the crowded 2000s do not flash past in a blur */
      const year = Math.round(Y0 + (Y1 - Y0) * (1 - Math.pow(1 - t, 1.9)));
      if (year !== shown) { shown = year; paintTo(year); }
      if (t < 1) requestAnimationFrame(step);
    };
    requestAnimationFrame(step);
  };
  return scene;
}

/* -------------------------------------------------------------- the cycle */
async function main() {
  const [data, world] = await Promise.all([
    fetch('data.json').then((r) => r.json()),
    fetch('world.json').then((r) => r.json()),
  ]);
  const all = data.translations;
  const byName = new Map(all.map((r) => [r.language, r]));

  /* Preview hooks, for working on one page without waiting for the cycle:
     ?only=Japanese,Arabic  plays just those, ?atlas=1 opens on the atlas,
     ?hold=1 freezes on the first page, ?year=1980 freezes the atlas at a
     given year. Harmless in production -- the wall loads the bare URL. */
  const q = new URLSearchParams(location.search);
  const only = (q.get('only') || '').split(',').map((s) => s.trim()).filter(Boolean);

  const pages = only.length
    ? only.map((n) => byName.get(n)).filter(Boolean)
    : SCOPE === 'all'
      ? all.filter((r) => r.year)
      : FEATURED.map((n) => byName.get(n)).filter(Boolean);

  /* Interleave the atlas between runs of language pages. */
  const seq = [];
  pages.forEach((rec, i) => {
    seq.push({ kind: 'lang', rec });
    if ((i + 1) % ATLAS_EVERY === 0 && i + 1 < pages.length) seq.push({ kind: 'atlas' });
  });
  if (!only.length) seq.push({ kind: 'atlas' });
  if (q.get('atlas')) seq.unshift({ kind: 'atlas' });
  const hold = q.get('hold');
  const frozenYear = q.has('year') ? parseInt(q.get('year'), 10) : null;

  const stage = document.getElementById('stage');
  let i = 0, showing = null;

  const show = () => {
    const item = seq[i % seq.length];
    i++;
    const scene = item.kind === 'atlas'
      ? atlasScene(world, all)
      : languageScene(world, all, item.rec);
    stage.appendChild(scene);
    if (scene._fit) scene._fit();        // measure before it is visible
    requestAnimationFrame(() => {
      scene.classList.add('live');
      /* ?year=1980 freezes the atlas at one year instead of sweeping. */
      if (frozenYear != null && scene._paintTo) scene._paintTo(frozenYear);
      else if (scene._play) scene._play();
    });

    const old = showing;
    showing = scene;
    if (old) {
      old.classList.remove('live');
      setTimeout(() => old.remove(), FADE_MS + 100);
    }
    if (!hold) setTimeout(show, item.kind === 'atlas' ? ATLAS_MS : PAGE_MS);
  };
  show();

  /* Re-fit on resize: the wall and a laptop preview are very different boxes. */
  let t;
  addEventListener('resize', () => {
    clearTimeout(t);
    t = setTimeout(() => { if (showing && showing._fit) showing._fit(); }, 200);
  });
}

main();
