[pi-day]
title = "Celebrate Pi Day"
experiences = [ "pi", "pi-circle", "pi-walk", "pi-triangle" ]

[interactive]
title = "Interactive Experiences"
experiences = [
  "fourier",
  "wind",
  "style-transfer",
  "fluid",
  "your-campus",
  "opinion-dynamics",
  "planes",
  "huffman",
  "gradient-descent",
  "twindragon",
  "leaves",
  "live-dashboard",
  "snowflake",
  "wave-lab",
  "barnsley-fern",
  "alg-infect",
  "neural-net-vis"
]

[game]
title = "BYU Games"
experiences = [ "liminus", "brawlers", "beatboxers", "neokaiju", "avastye", "solarshowdown" ]

[animation]
title = "BYU Animation"
experiences = [
  "taijitu",
  "grendel",
  "death",
  "estefan",
  "metro",
  "owned",
  "papa",
  "rams-horn",
  "salt",
  "stowaway",
  "cenote",
  "witchscat",
  "studacc",
  "loveandgold",
  "kites",
  "lemmings",
  "honey"
]

[graduation]
title = "Graduation"
experiences = [
  "graduation",
  "photo-op"
]

[christmas]
title = "Christmas"
experiences = [ "cmas-snowglobe", "cmas-finals" ]

[cpms50]
title = "CPMS is 50"
experiences = [ "cpms50" ]


[lds]
title = "LDS-themed experiences"
experiences = [
  "temple-photo-op"
]

[archive]
title = "Archived Experiences"
experiences = [
  "maze-generation",
  "bus-bunching",
  "asteroids",
  "sorting",
  "butterfly",
  "ifs",
  "hilbert",
  "mirror-of-whimsy",
  "ai-artist",
  "hilbert",
  "life",
  "stylegan",
  "pong4",
  "fractals",
  "ifs"
]
