/** @jsxImportSource @emotion/react */
/**
 * Quadtree — phone controls.
 *
 * Generated by scripts/package-single.py from the Data Structures project.
 * The wall sends its actions in a {type:"state"} message (see footron.js); the
 * list below is only a fallback for before the first state arrives.
 *
 *   -> wall   { type: "hello" } | { type: "action", value } |
 *             { type: "pause", value } | { type: "speed", value } | { type: "release" }
 *   <- wall   { type: "state", scene, mode, paused, speed, scenes, actions }
 */
import React, { useCallback, useEffect, useRef, useState } from "react";
import { css } from "@emotion/react";
import Button from "@material-ui/core/Button";
import Typography from "@material-ui/core/Typography";
import PauseIcon from "@material-ui/icons/Pause";
import PlayArrowIcon from "@material-ui/icons/PlayArrow";
import { useMessaging } from "@footron/controls-client";

const TITLE = "Quadtree";
const BLURB = "Squares split only where points crowd. Add flocks, scatter them, or toggle the search.";
const FALLBACK_ACTIONS = [{"id": "burst", "label": "Add a flock"}, {"id": "thin", "label": "Remove points"}, {"id": "scatter", "label": "Scatter"}, {"id": "query", "label": "Query on/off"}, {"id": "links", "label": "Neighbours on/off"}];
const SPEEDS = [0.5, 1, 2];

const containerStyle = css`
  display: flex;
  flex-direction: column;
  gap: 16px;
  padding: 24px;
  max-width: 440px;
  margin: 0 auto;
`;
const hintStyle = css`
  opacity: 0.7;
  line-height: 1.5;
`;
const sectionTitleStyle = css`
  font-size: 12px;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  opacity: 0.55;
  margin-bottom: -6px;
`;
const gridStyle = css`
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 10px;
`;
const rowStyle = css`
  display: flex;
  gap: 10px;
`;
const bigButton = css`
  min-height: 56px;
  text-transform: none;
  font-size: 15px;
`;

const Controls = () => {
  const [actions, setActions] = useState(FALLBACK_ACTIONS);
  const [paused, setPaused] = useState(false);
  const [speed, setSpeed] = useState(1);

  const { sendMessage } = useMessaging((msg) => {
    if (!msg || msg.type !== "state") return;
    if (Array.isArray(msg.actions) && msg.actions.length) setActions(msg.actions);
    if (typeof msg.paused === "boolean") setPaused(msg.paused);
    if (typeof msg.speed === "number") setSpeed(msg.speed);
  });

  // Once, not per render: sendMessage may change identity and every reply re-renders.
  const greeted = useRef(false);
  useEffect(() => {
    if (greeted.current) return undefined;
    greeted.current = true;
    const hello = () => Promise.resolve(sendMessage({ type: "hello" })).catch(() => {});
    hello();
    const t = setTimeout(hello, 1500);
    return () => clearTimeout(t);
  }, [sendMessage]);

  const doAction = useCallback((id) => sendMessage({ type: "action", value: id }), [sendMessage]);
  const togglePause = useCallback(() => {
    const v = !paused;
    setPaused(v);
    sendMessage({ type: "pause", value: v });
  }, [paused, sendMessage]);
  const pickSpeed = useCallback((v) => { setSpeed(v); sendMessage({ type: "speed", value: v }); }, [sendMessage]);
  const release = useCallback(() => { sendMessage({ type: "release" }); setPaused(false); setSpeed(1); }, [sendMessage]);

  return (
    <div css={containerStyle}>
      <Typography variant="h6">{TITLE}</Typography>
      <Typography variant="body2" css={hintStyle}>{BLURB}</Typography>

      <div css={sectionTitleStyle}>Try it</div>
      <div css={gridStyle}>
        {actions.map((a) => (
          <Button key={a.id} css={bigButton} variant="contained" color="primary" onClick={() => doAction(a.id)}>
            {a.label}
          </Button>
        ))}
      </div>

      <div css={sectionTitleStyle}>Playback</div>
      <div css={rowStyle}>
        <Button onClick={togglePause} startIcon={paused ? <PlayArrowIcon /> : <PauseIcon />} variant="outlined" fullWidth>
          {paused ? "Play" : "Pause"}
        </Button>
        {SPEEDS.map((v) => (
          <Button key={v} onClick={() => pickSpeed(v)} variant={speed === v ? "contained" : "outlined"}>
            {v}×
          </Button>
        ))}
      </div>

      <Button onClick={release} variant="outlined" fullWidth>
        Let the wall carry on
      </Button>
      <Typography variant="body2" css={hintStyle}>
        Leave it alone for a minute and the wall goes back to playing on its own.
      </Typography>
    </div>
  );
};

export default Controls;
