/* Generated by npm run controls:catalog — do not edit by hand.
 *
 * 284 items the wall can show, in 16 topics. The topics are a
 * finding aid for this panel only: the wall shows nine tiles with no grouping,
 * so every label here has to stand on its own. Regenerate from the Dashboard
 * repo whenever the dashboard gains or renames a metric.
 */
export const SLOTS = 9;
export const HOLD_MS = 120000;
export const PACES = ["slow","calm","quick"];

export const TOPICS = [
  {
    "id": "here",
    "title": "Where you are",
    "items": [
      {
        "id": "lat",
        "label": "Latitude of the Talmage Building"
      },
      {
        "id": "lon",
        "label": "Longitude of the Talmage Building"
      },
      {
        "id": "elev",
        "label": "Elevation of the Talmage Building"
      },
      {
        "id": "core",
        "label": "Distance Down to Earth's Core"
      },
      {
        "id": "equator",
        "label": "Distance to the Equator"
      },
      {
        "id": "npole",
        "label": "Distance to the North Pole"
      },
      {
        "id": "antipode",
        "label": "Distance to the Antipode"
      },
      {
        "id": "city-Salt Lake City",
        "label": "Distance to Salt Lake City"
      },
      {
        "id": "city-New York",
        "label": "Distance to New York"
      },
      {
        "id": "city-London",
        "label": "Distance to London"
      },
      {
        "id": "city-Tokyo",
        "label": "Distance to Tokyo"
      },
      {
        "id": "city-Sydney",
        "label": "Distance to Sydney"
      },
      {
        "id": "city-South Pole",
        "label": "Distance to the South Pole"
      },
      {
        "id": "cm-to-Harold B. Lee Library",
        "label": "Walk to the Harold B. Lee Library"
      },
      {
        "id": "cm-to-the Wilkinson Center",
        "label": "Walk to the Wilkinson Center"
      },
      {
        "id": "cm-to-the Marriott Center",
        "label": "Walk to the Marriott Center"
      },
      {
        "id": "cm-to-LaVell Edwards Stadium",
        "label": "Walk to LaVell Edwards Stadium"
      },
      {
        "id": "cm-to-Y Mountain summit",
        "label": "Walk to the Y Mountain Summit"
      },
      {
        "id": "cm-to-Provo City Center Temple",
        "label": "Walk to the Provo City Center Temple"
      },
      {
        "id": "cm-to-Provo Airport",
        "label": "Walk to Provo Airport"
      }
    ]
  },
  {
    "id": "motion",
    "title": "How fast you are moving",
    "items": [
      {
        "id": "spin",
        "label": "Your Speed from Earth's Spin"
      },
      {
        "id": "orbit-speed",
        "label": "Your Speed Around the Sun"
      },
      {
        "id": "galaxy-speed",
        "label": "Your Speed Around the Galaxy"
      },
      {
        "id": "cmb-speed",
        "label": "Your Speed Against the Cosmic Background"
      },
      {
        "id": "iss",
        "label": "Distance to the Space Station"
      },
      {
        "id": "iss-speed",
        "label": "Space Station Ground Speed"
      },
      {
        "id": "sun-dist",
        "label": "Distance to the Sun"
      },
      {
        "id": "moon-dist",
        "label": "Distance to the Moon"
      }
    ]
  },
  {
    "id": "weather",
    "title": "The air over Provo",
    "items": [
      {
        "id": "f",
        "label": "Temperature Over Provo, Fahrenheit"
      },
      {
        "id": "c",
        "label": "Temperature Over Provo, Celsius"
      },
      {
        "id": "k",
        "label": "Temperature Over Provo, Kelvin"
      },
      {
        "id": "thermo",
        "label": "The Thermometer Over Provo"
      },
      {
        "id": "spark",
        "label": "Three Days of Provo Temperature"
      },
      {
        "id": "rankine",
        "label": "Temperature Over Provo, Rankine"
      },
      {
        "id": "reaumur",
        "label": "Temperature Over Provo, Réaumur"
      },
      {
        "id": "delisle",
        "label": "Temperature Over Provo, Delisle"
      },
      {
        "id": "romer",
        "label": "Temperature Over Provo, Rømer"
      },
      {
        "id": "newton",
        "label": "Temperature Over Provo, Newton"
      },
      {
        "id": "dew",
        "label": "Dew Point Over Provo"
      },
      {
        "id": "humidity",
        "label": "Relative Humidity Over Provo"
      },
      {
        "id": "cloud",
        "label": "Cloud Cover Over Provo"
      },
      {
        "id": "wind",
        "label": "Wind Speed Over Provo"
      },
      {
        "id": "pressure",
        "label": "Barometric Pressure Over Provo"
      },
      {
        "id": "density",
        "label": "Air Density Over Provo"
      },
      {
        "id": "sound",
        "label": "Speed of Sound in Today's Air"
      },
      {
        "id": "uv",
        "label": "Peak UV Index in Provo Today"
      },
      {
        "id": "precip",
        "label": "Chance of Precipitation in Provo"
      },
      {
        "id": "vs-body",
        "label": "How Far the Air Is Below Body Temperature"
      },
      {
        "id": "vs-sun",
        "label": "How Much Cooler Than the Sun's Surface"
      },
      {
        "id": "vs-space",
        "label": "How Much Warmer Than Deep Space"
      },
      {
        "id": "cm-aqi",
        "label": "Air Quality Index Over Provo"
      },
      {
        "id": "cm-pm25",
        "label": "Fine Particulate Over Provo, PM2.5"
      },
      {
        "id": "cm-pm10",
        "label": "Coarse Particulate Over Provo, PM10"
      },
      {
        "id": "cm-ozone",
        "label": "Ground-Level Ozone Over Provo"
      },
      {
        "id": "cm-dust",
        "label": "Airborne Dust Over Provo"
      },
      {
        "id": "w-alerts",
        "label": "Weather Warnings in Force for Provo"
      }
    ]
  },
  {
    "id": "time",
    "title": "What time it is",
    "items": [
      {
        "id": "local",
        "label": "The Time in Provo"
      },
      {
        "id": "utc",
        "label": "Coordinated Universal Time"
      },
      {
        "id": "tz-utc",
        "label": "The Time in London"
      },
      {
        "id": "tz-ny",
        "label": "The Time in New York"
      },
      {
        "id": "tz-tokyo",
        "label": "The Time in Tokyo"
      },
      {
        "id": "tz-syd",
        "label": "The Time in Sydney"
      },
      {
        "id": "unix",
        "label": "Unix Epoch Seconds"
      },
      {
        "id": "unix-ms",
        "label": "Milliseconds Since the Unix Epoch"
      },
      {
        "id": "jd",
        "label": "Julian Date"
      },
      {
        "id": "mjd",
        "label": "Modified Julian Date"
      },
      {
        "id": "beats",
        "label": "Swatch Internet Time"
      },
      {
        "id": "mtc",
        "label": "Mars Coordinated Time"
      },
      {
        "id": "lst",
        "label": "Local Sidereal Time in Provo"
      },
      {
        "id": "day-pct",
        "label": "How Much of Today Has Gone"
      },
      {
        "id": "year-pct",
        "label": "How Much of This Year Has Gone"
      },
      {
        "id": "newyear",
        "label": "Until the New Year"
      },
      {
        "id": "leapday",
        "label": "Until the Next Leap Day"
      },
      {
        "id": "since-epoch",
        "label": "Since the Unix Epoch"
      },
      {
        "id": "since-j2000",
        "label": "Days Since J2000.0"
      },
      {
        "id": "y2038",
        "label": "Until the Year 2038 Problem"
      },
      {
        "id": "utah",
        "label": "Since Utah Became a State"
      },
      {
        "id": "genconf",
        "label": "Until General Conference"
      },
      {
        "id": "genconf-session",
        "label": "Until the Next Conference Session"
      },
      {
        "id": "genconf-since",
        "label": "Since the Last General Conference"
      }
    ]
  },
  {
    "id": "rotation",
    "title": "Whether Earth is keeping time",
    "items": [
      {
        "id": "er-lod",
        "label": "How Much Today Overran 24 Hours"
      },
      {
        "id": "er-rotation",
        "label": "Today's Actual Earth Rotation"
      },
      {
        "id": "er-lost",
        "label": "Time the Earth Has Lost Today"
      },
      {
        "id": "er-ut1",
        "label": "UT1 Minus UTC"
      },
      {
        "id": "er-leap-room",
        "label": "Room Left Before a Leap Second"
      },
      {
        "id": "er-leap-when",
        "label": "When a Leap Second Is Due at This Rate"
      },
      {
        "id": "er-pole",
        "label": "How Far Earth's Pole Has Wandered"
      },
      {
        "id": "er-xpole",
        "label": "Earth's Polar Motion, X"
      },
      {
        "id": "er-ypole",
        "label": "Earth's Polar Motion, Y"
      },
      {
        "id": "er-omega",
        "label": "Earth's Angular Velocity"
      },
      {
        "id": "er-dx",
        "label": "Celestial Pole Offset, dX"
      },
      {
        "id": "er-dy",
        "label": "Celestial Pole Offset, dY"
      }
    ]
  },
  {
    "id": "sky",
    "title": "The sky over Provo",
    "items": [
      {
        "id": "sky",
        "label": "The Sky Over Provo Right Now"
      },
      {
        "id": "moondisc",
        "label": "Tonight's Moon Phase"
      },
      {
        "id": "sunpath",
        "label": "The Sun's Path Over Provo Today"
      },
      {
        "id": "sunset",
        "label": "Until Sunset in Provo"
      },
      {
        "id": "sunrise",
        "label": "Until Sunrise in Provo"
      },
      {
        "id": "sunrise-t",
        "label": "Sunrise in Provo Today"
      },
      {
        "id": "sunset-t",
        "label": "Sunset in Provo Today"
      },
      {
        "id": "noon",
        "label": "Solar Noon in Provo Today"
      },
      {
        "id": "daylength",
        "label": "Hours of Daylight in Provo Today"
      },
      {
        "id": "sun-alt",
        "label": "The Sun's Altitude Over Provo"
      },
      {
        "id": "sun-az",
        "label": "The Sun's Compass Bearing from Provo"
      },
      {
        "id": "moon-alt",
        "label": "The Moon's Altitude Over Provo"
      },
      {
        "id": "moon-az",
        "label": "The Moon's Compass Bearing from Provo"
      },
      {
        "id": "illum",
        "label": "How Much of the Moon Is Lit"
      },
      {
        "id": "age",
        "label": "Days Since the New Moon"
      },
      {
        "id": "moon-ang",
        "label": "Apparent Size of the Moon"
      },
      {
        "id": "sun-ang",
        "label": "Apparent Size of the Sun"
      }
    ]
  },
  {
    "id": "solar",
    "title": "The solar system",
    "items": [
      {
        "id": "au",
        "label": "Earth's Distance from the Sun"
      },
      {
        "id": "light-sun",
        "label": "How Long Sunlight Takes to Reach Provo"
      },
      {
        "id": "light-moon",
        "label": "How Long Moonlight Takes to Reach Provo"
      },
      {
        "id": "orbit-progress",
        "label": "Earth's Progress Around the Sun"
      },
      {
        "id": "orbit-km",
        "label": "Distance Earth Has Flown This Year"
      },
      {
        "id": "rotations",
        "label": "Earth Rotations Since J2000.0"
      },
      {
        "id": "declination",
        "label": "Solar Declination"
      },
      {
        "id": "eot",
        "label": "Equation of Time"
      },
      {
        "id": "fullmoon",
        "label": "Until the Full Moon"
      },
      {
        "id": "newmoon",
        "label": "Until the New Moon"
      },
      {
        "id": "perigee",
        "label": "Until the Moon's Closest Approach"
      },
      {
        "id": "apogee",
        "label": "Until the Moon's Furthest Point"
      },
      {
        "id": "equinox",
        "label": "Until the Autumn Equinox"
      },
      {
        "id": "solstice",
        "label": "Until the Winter Solstice"
      },
      {
        "id": "perihelion",
        "label": "Until Earth Is Closest to the Sun"
      },
      {
        "id": "aphelion",
        "label": "Until Earth Is Furthest from the Sun"
      },
      {
        "id": "halley",
        "label": "Until Halley's Comet Returns"
      },
      {
        "id": "eclipse",
        "label": "Until the Next Total Solar Eclipse"
      },
      {
        "id": "eclipse-us",
        "label": "Until the Next U.S. Total Solar Eclipse"
      },
      {
        "id": "lunar-eclipse",
        "label": "Until the Next Total Lunar Eclipse"
      },
      {
        "id": "mercury",
        "label": "Until the Next Transit of Mercury"
      },
      {
        "id": "venus",
        "label": "Until the Next Transit of Venus"
      },
      {
        "id": "voyager1",
        "label": "Voyager 1's Distance from the Sun"
      },
      {
        "id": "voyager2",
        "label": "Voyager 2's Distance from the Sun"
      }
    ]
  },
  {
    "id": "space",
    "title": "Space weather and spaceflight",
    "items": [
      {
        "id": "sw-kp",
        "label": "Planetary K Index"
      },
      {
        "id": "sw-aurora",
        "label": "Aurora Visible from Provo"
      },
      {
        "id": "sw-wind",
        "label": "Solar Wind Speed"
      },
      {
        "id": "sw-transit",
        "label": "Solar Wind Transit Time from L1"
      },
      {
        "id": "sw-bt",
        "label": "Interplanetary Magnetic Field, Bt"
      },
      {
        "id": "sw-bz",
        "label": "Interplanetary Magnetic Field, Bz"
      },
      {
        "id": "sw-flare",
        "label": "Current Solar Flare Class"
      },
      {
        "id": "sw-xray",
        "label": "Solar X-ray Flux"
      },
      {
        "id": "sw-ssn",
        "label": "Sunspot Number Today"
      },
      {
        "id": "sw-f107",
        "label": "F10.7 cm Solar Radio Flux"
      },
      {
        "id": "sw-r",
        "label": "Radio Blackout Level"
      },
      {
        "id": "sw-s",
        "label": "Radiation Storm Level"
      },
      {
        "id": "sw-launch",
        "label": "Until the Next Rocket Launch"
      },
      {
        "id": "sw-launch2",
        "label": "Until the Rocket Launch After Next"
      },
      {
        "id": "since-moon",
        "label": "Since the First Moon Landing"
      },
      {
        "id": "since-sputnik",
        "label": "Since Sputnik Launched"
      }
    ]
  },
  {
    "id": "planet",
    "title": "The planet's vital signs",
    "items": [
      {
        "id": "population",
        "label": "World Population"
      },
      {
        "id": "births",
        "label": "Babies Born Worldwide Today"
      },
      {
        "id": "deaths",
        "label": "Deaths Worldwide Today"
      },
      {
        "id": "net",
        "label": "Net World Population Growth Today"
      },
      {
        "id": "co2",
        "label": "Atmospheric CO₂"
      },
      {
        "id": "co2-preindustrial",
        "label": "CO₂ Above Pre-Industrial Levels"
      },
      {
        "id": "ch4",
        "label": "Atmospheric Methane"
      },
      {
        "id": "anomaly",
        "label": "Global Temperature Anomaly"
      },
      {
        "id": "anomaly-preind",
        "label": "Warming Since Pre-Industrial Times"
      },
      {
        "id": "sea",
        "label": "Sea Level Rise Since 1993"
      },
      {
        "id": "sea-trend",
        "label": "Rate of Sea Level Rise"
      },
      {
        "id": "solar-power",
        "label": "Sunlight Hitting Earth"
      },
      {
        "id": "solar-today",
        "label": "Solar Energy Earth Received Today"
      },
      {
        "id": "lightning",
        "label": "Lightning Strikes Worldwide Today"
      },
      {
        "id": "fireballs",
        "label": "Fireballs Detected This Year"
      },
      {
        "id": "fireball-last",
        "label": "Since the Last Fireball Detected"
      },
      {
        "id": "fireball-biggest",
        "label": "Largest Fireball This Year"
      },
      {
        "id": "earth-age",
        "label": "Age of the Earth"
      },
      {
        "id": "universe-age",
        "label": "Age of the Universe"
      }
    ]
  },
  {
    "id": "seismic",
    "title": "Earthquakes",
    "items": [
      {
        "id": "q-total",
        "label": "Earthquakes Worldwide Today"
      },
      {
        "id": "q-hour",
        "label": "Earthquakes Worldwide in the Past Hour"
      },
      {
        "id": "q-rate",
        "label": "Earthquakes Per Hour Worldwide Today"
      },
      {
        "id": "q-largest",
        "label": "Strongest Earthquake on Earth Today"
      },
      {
        "id": "q-latest",
        "label": "Most Recent Earthquake Anywhere"
      },
      {
        "id": "q-m45",
        "label": "Earthquakes of M4.5 or Greater Today"
      },
      {
        "id": "q-energy",
        "label": "Seismic Energy Released Worldwide Today"
      },
      {
        "id": "q-eqmag",
        "label": "Today's Earthquakes Added Into One"
      },
      {
        "id": "q-sig",
        "label": "Most Significant Earthquake Today"
      },
      {
        "id": "q-alert",
        "label": "Highest PAGER Alert Today"
      },
      {
        "id": "q-shaking",
        "label": "Strongest Shaking Felt on Earth Today"
      },
      {
        "id": "q-felt",
        "label": "“Did You Feel It?” Reports Worldwide Today"
      },
      {
        "id": "q-deepest",
        "label": "Deepest Earthquake on Earth Today"
      },
      {
        "id": "q-meandepth",
        "label": "Mean Depth of Today's Earthquakes"
      },
      {
        "id": "q-blasts",
        "label": "Quarry Blasts Recorded Worldwide Today"
      },
      {
        "id": "q-reviewed",
        "label": "Today's Earthquakes Reviewed by a Seismologist"
      },
      {
        "id": "q-tsunami",
        "label": "Tsunami Flags Raised Worldwide Today"
      },
      {
        "id": "q-utah",
        "label": "Earthquakes in Utah Today"
      },
      {
        "id": "q-nearest",
        "label": "Distance to Today's Nearest Earthquake"
      },
      {
        "id": "q-depth",
        "label": "Depth of the Nearest Earthquake Today"
      },
      {
        "id": "q-lastnear",
        "label": "Since the Last Earthquake Near Provo"
      },
      {
        "id": "q-lastm3",
        "label": "Since the Last M3 or Greater Near Provo"
      },
      {
        "id": "q-near30",
        "label": "Earthquakes Within 100 km of Provo, Past 30 Days"
      },
      {
        "id": "q-near365",
        "label": "Earthquakes Within 100 km of Provo, Past Year"
      },
      {
        "id": "q-bigyear",
        "label": "Largest Earthquake Near Provo This Year"
      },
      {
        "id": "q-bigever",
        "label": "Largest Earthquake Near Provo Since 1900"
      }
    ]
  },
  {
    "id": "water",
    "title": "Utah water",
    "items": [
      {
        "id": "w-gsl",
        "label": "Great Salt Lake Elevation"
      },
      {
        "id": "w-gsl-low",
        "label": "Great Salt Lake Above the 2022 Record Low"
      },
      {
        "id": "w-gsl-healthy",
        "label": "Great Salt Lake Below the Healthy Range"
      },
      {
        "id": "w-provo",
        "label": "Provo River Streamflow"
      },
      {
        "id": "w-gage",
        "label": "Provo River Gage Height"
      },
      {
        "id": "w-daily",
        "label": "Water Down the Provo River in a Day"
      }
    ]
  },
  {
    "id": "fire",
    "title": "Wildfire",
    "items": [
      {
        "id": "wf-utah",
        "label": "Wildfires Burning in Utah"
      },
      {
        "id": "wf-acres",
        "label": "Acres Alight in Utah"
      },
      {
        "id": "wf-crews",
        "label": "Firefighters Deployed in Utah"
      },
      {
        "id": "wf-nearest",
        "label": "Distance to the Nearest Utah Wildfire"
      },
      {
        "id": "wf-nearest-active",
        "label": "Distance to the Nearest Uncontained Utah Wildfire"
      },
      {
        "id": "wf-contained",
        "label": "Containment of the Nearest Utah Wildfire"
      },
      {
        "id": "wf-cause",
        "label": "Cause of the Nearest Utah Wildfire"
      },
      {
        "id": "wf-burning",
        "label": "Since the Nearest Utah Wildfire Started"
      },
      {
        "id": "wf-newest",
        "label": "Since Utah's Newest Wildfire Started"
      },
      {
        "id": "wf-largest",
        "label": "Largest Wildfire Burning in Utah"
      },
      {
        "id": "wf-national",
        "label": "Wildfires Burning Nationwide"
      }
    ]
  },
  {
    "id": "aviation",
    "title": "Aircraft overhead",
    "items": [
      {
        "id": "av-count",
        "label": "Aircraft Over Utah Right Now"
      },
      {
        "id": "av-nearest",
        "label": "Distance to the Nearest Aircraft"
      },
      {
        "id": "av-near-alt",
        "label": "Altitude of the Nearest Aircraft"
      },
      {
        "id": "av-airframe",
        "label": "Type of the Nearest Aircraft"
      },
      {
        "id": "av-highest",
        "label": "Highest Aircraft Over Utah"
      },
      {
        "id": "av-mean",
        "label": "Mean Cruising Altitude Over Utah"
      },
      {
        "id": "av-fastest",
        "label": "Fastest Aircraft Over Utah"
      },
      {
        "id": "av-mach",
        "label": "Fastest Aircraft Over Utah, in Mach"
      },
      {
        "id": "av-route",
        "label": "The Nearest Airliner's Route"
      },
      {
        "id": "av-journey",
        "label": "How Much of the Nearest Airliner's Flight Is Done"
      },
      {
        "id": "av-flown",
        "label": "How Far the Nearest Airliner Has Flown"
      },
      {
        "id": "av-togo",
        "label": "How Far the Nearest Airliner Has Left to Fly"
      }
    ]
  },
  {
    "id": "campus",
    "title": "BYU campus",
    "items": [
      {
        "id": "cm-session",
        "label": "Are BYU Classes in Session Right Now"
      },
      {
        "id": "cm-progress",
        "label": "BYU Semester Progress"
      },
      {
        "id": "cm-elapsed",
        "label": "BYU Class Days Elapsed This Semester"
      },
      {
        "id": "cm-tofinals",
        "label": "BYU Class Days Left Before Finals"
      },
      {
        "id": "cm-devotional",
        "label": "Until the Next BYU Devotional"
      },
      {
        "id": "byu-classes",
        "label": "Until BYU Classes Begin"
      },
      {
        "id": "byu-lastday",
        "label": "Until BYU's Last Day of Class"
      },
      {
        "id": "byu-study",
        "label": "Until BYU Exam Preparation Day"
      },
      {
        "id": "byu-finals",
        "label": "Until BYU Finals Begin"
      },
      {
        "id": "byu-finals-end",
        "label": "Until BYU Finals Are Over"
      },
      {
        "id": "byu-holiday",
        "label": "Until the Next BYU Holiday"
      },
      {
        "id": "byu-holiday-next",
        "label": "Until the BYU Holiday After Next"
      },
      {
        "id": "byu-classdays",
        "label": "BYU Class Days Until the Next Holiday"
      },
      {
        "id": "byu-holidays-term",
        "label": "BYU Holidays Left This Semester"
      },
      {
        "id": "byu",
        "label": "Since BYU Was Founded"
      }
    ]
  },
  {
    "id": "sports",
    "title": "Cougar sports",
    "items": [
      {
        "id": "sp-riv-fb",
        "label": "Since Utah Beat BYU in Football"
      },
      {
        "id": "sp-riv-bb",
        "label": "Since Utah Beat BYU in Basketball"
      },
      {
        "id": "sp-next",
        "label": "Until the Next BYU Football Game"
      },
      {
        "id": "sp-fb-standing",
        "label": "BYU Football in the Big 12"
      },
      {
        "id": "sp-fb-yards",
        "label": "BYU Football Total Offense"
      },
      {
        "id": "sp-fb-points",
        "label": "BYU Football Points Scored"
      },
      {
        "id": "sp-fb-pass",
        "label": "BYU Football Passing Yards"
      },
      {
        "id": "sp-fb-rush",
        "label": "BYU Football Rushing Yards"
      },
      {
        "id": "sp-fb-td",
        "label": "BYU Football Touchdowns"
      },
      {
        "id": "sp-fb-first",
        "label": "BYU Football First Downs"
      },
      {
        "id": "sp-fb-third",
        "label": "BYU Football Third-Down Conversions"
      },
      {
        "id": "sp-fb-fourth",
        "label": "BYU Football Fourth-Down Conversions"
      },
      {
        "id": "sp-fb-perplay",
        "label": "BYU Football Yards Per Play"
      },
      {
        "id": "sp-fb-turnover",
        "label": "BYU Football Turnover Differential"
      },
      {
        "id": "sp-fb-sacks",
        "label": "BYU Football Sacks Recorded"
      },
      {
        "id": "sp-fb-poss",
        "label": "BYU Football Time of Possession Per Game"
      },
      {
        "id": "sp-fb-pen",
        "label": "BYU Football Penalty Yards"
      },
      {
        "id": "sp-mbb-points",
        "label": "BYU Men's Basketball Points"
      },
      {
        "id": "sp-mbb-fg",
        "label": "BYU Men's Basketball Field Goal Percentage"
      },
      {
        "id": "sp-mbb-three",
        "label": "BYU Men's Basketball Three-Point Percentage"
      },
      {
        "id": "sp-mbb-ft",
        "label": "BYU Men's Basketball Free Throw Percentage"
      },
      {
        "id": "sp-mbb-reb",
        "label": "BYU Men's Basketball Rebounds"
      },
      {
        "id": "sp-mbb-ast",
        "label": "BYU Men's Basketball Assists"
      },
      {
        "id": "sp-mbb-def",
        "label": "BYU Men's Basketball Steals & Blocks"
      },
      {
        "id": "sp-mbb-standing",
        "label": "BYU Men's Basketball Standing"
      },
      {
        "id": "sp-wbb-points",
        "label": "BYU Women's Basketball Points"
      },
      {
        "id": "sp-wbb-fg",
        "label": "BYU Women's Basketball Field Goal Percentage"
      },
      {
        "id": "sp-wbb-three",
        "label": "BYU Women's Basketball Three-Point Percentage"
      },
      {
        "id": "sp-wbb-ft",
        "label": "BYU Women's Basketball Free Throw Percentage"
      },
      {
        "id": "sp-wbb-reb",
        "label": "BYU Women's Basketball Rebounds"
      },
      {
        "id": "sp-wbb-ast",
        "label": "BYU Women's Basketball Assists"
      },
      {
        "id": "sp-wbb-standing",
        "label": "BYU Women's Basketball Standing"
      },
      {
        "id": "sp-wsoccer",
        "label": "Until the Next BYU Women's Soccer Match"
      },
      {
        "id": "sp-wvb",
        "label": "Until the Next BYU Women's Volleyball Match"
      },
      {
        "id": "sp-mvb",
        "label": "BYU Men's Volleyball Standing"
      },
      {
        "id": "sp-baseball",
        "label": "BYU Baseball Record"
      }
    ]
  },
  {
    "id": "internet",
    "title": "The internet, live",
    "items": [
      {
        "id": "net-eps",
        "label": "Wikipedia Changes Per Second"
      },
      {
        "id": "net-lastmin",
        "label": "Wikipedia Changes in the Last Minute"
      },
      {
        "id": "net-en",
        "label": "English Wikipedia Changes Per Minute"
      },
      {
        "id": "net-new",
        "label": "New Wikipedia Pages Per Minute"
      },
      {
        "id": "net-bots",
        "label": "Wikipedia Changes Written by Bots"
      },
      {
        "id": "net-bytes",
        "label": "Bytes Written to Wikipedia Per Minute"
      },
      {
        "id": "net-latest",
        "label": "The Most Recent Wikipedia Edit"
      },
      {
        "id": "net-certs",
        "label": "Certificates in the Largest Public CT Log"
      },
      {
        "id": "net-certrate",
        "label": "Certificates Entering the Busiest CT Log"
      },
      {
        "id": "net-certtotal",
        "label": "Entries Across All Public CT Logs"
      }
    ]
  }
];

export const ITEMS = TOPICS.flatMap((t) =>
  t.items.map((i) => ({ ...i, topic: t.id, topicTitle: t.title }))
);

export const LABELS = Object.fromEntries(ITEMS.map((i) => [i.id, i.label]));
