/** @jsxImportSource @emotion/react */
import { css } from "@emotion/react";
import React, { useState } from "react";
import { useMessaging } from "@footron/controls-client";
import {
  FormControl,
  NativeSelect,
  InputLabel,
  Checkbox,
  FormControlLabel,
  FormGroup, Slider
} from "@material-ui/core";
import { useCallback } from "react";

const containerStyle = css`
  padding: 16px;
  overflow-x: hidden;

  p {
    margin: 0 0 16px;
  }
`;

const names = [
[ 0, 'Carter Adams' ],
[ 1, 'Gwang Hong Ahn' ],
[ 2, 'Jayden Allen' ],
[ 3, 'Mali Allen' ],
[ 4, 'Zachary Allen' ],
[ 5, 'Ethan Alvey' ],
[ 6, 'Tessa Andersen' ],
[ 7, 'Taylor Archibald' ],
[ 8, 'Derek Ashby' ],
[ 9, 'Connor Ashton' ],
[ 10, 'Nick Austin' ],
[ 11, 'Taylor Aydelotte' ],
[ 12, 'Matthew Bailey' ],
[ 13, 'Jared Bake' ],
[ 14, 'Dallin Baker' ],
[ 15, 'Jonathan Ballard' ],
[ 16, 'Quenton Barger' ],
[ 17, 'Connor Barrett' ],
[ 18, 'Eli Barton' ],
[ 19, 'David Bauch' ],
[ 20, 'Chapman Beaird' ],
[ 21, 'Austin Beckstead' ],
[ 22, 'Brendan Behunin' ],
[ 23, 'Garrett Bennett' ],
[ 24, 'Bentley Bigelow' ],
[ 25, 'Talmage Bird' ],
[ 26, 'Ethaniel Bishop' ],
[ 27, 'Savannah Bjorkman' ],
[ 28, 'Kennion Black' ],
[ 29, 'Tyler Blackham' ],
[ 30, 'Spencer Blanchard' ],
[ 31, 'Braden Bledsoe' ],
[ 32, 'David Bloomfield' ],
[ 33, 'Trevor Bond' ],
[ 34, 'Wesley Borden' ],
[ 35, 'Carlos Borja Leano' ],
[ 36, 'McKay Bowcut' ],
[ 37, 'Ezra Bradley' ],
[ 38, 'Caleb Bradshaw' ],
[ 39, 'Benjamin Brittain' ],
[ 40, 'Jordan Brockbank' ],
[ 41, 'Chloe Brown' ],
[ 42, 'Tristan Brown' ],
[ 43, 'Nathan Bulloch' ],
[ 44, 'Jacob Bullock' ],
[ 45, 'Alex Burgess' ],
[ 46, 'Tanner Buss' ],
[ 47, 'Caleb Calderwood' ],
[ 48, 'Logan Carpenter' ],
[ 49, 'Chance Carr' ],
[ 50, 'Harrison Casper' ],
[ 51, 'James Chan' ],
[ 52, 'Kirsten Chapman' ],
[ 53, 'Phoebe Chen' ],
[ 54, 'Steven Cheng' ],
[ 55, 'Tanner Child' ],
[ 56, 'Ben Christensen' ],
[ 57, 'Josh Christensen' ],
[ 58, 'Connor Cihula' ],
[ 59, 'Josh Clancy' ],
[ 60, 'Dallin Clark' ],
[ 61, 'Ellie Clark' ],
[ 62, 'Michael Clark' ],
[ 63, 'William Clayton' ],
[ 64, 'Spencer Clingo' ],
[ 65, 'Lucy Collins' ],
[ 66, 'Matthew Crandall' ],
[ 67, 'Michael Crandall' ],
[ 68, 'Jacobus Crawford' ],
[ 69, 'Foster Curtis' ],
[ 70, 'Koby Cutler' ],
[ 71, 'Alec Davis' ],
[ 72, 'Emily De Graw' ],
[ 73, 'Alexander Densley' ],
[ 74, 'Kevin Dixon' ],
[ 75, 'Nathan Dong' ],
[ 76, 'Tyler Driggs' ],
[ 77, 'Brennan Duncan' ],
[ 78, 'Hyrum Durfee' ],
[ 79, 'Eli Ellsworth' ],
[ 80, 'Ammon Elzinga' ],
[ 81, 'Tanner England' ],
[ 82, 'Matt Feist' ],
[ 83, 'Julio Ferreira' ],
[ 84, 'Keaton Folsom' ],
[ 85, 'Minami Ford' ],
[ 86, 'Davis Forster' ],
[ 87, 'Devin Frandsen' ],
[ 88, 'Kyle Frazier' ],
[ 89, 'Samuel Galbraith' ],
[ 90, 'Andrew Gardner' ],
[ 91, 'Grant Gardner' ],
[ 92, 'Jaxon Gardner' ],
[ 93, 'Sydney Gardner' ],
[ 94, 'Rachel George' ],
[ 95, 'Samuel Gerlach' ],
[ 96, 'Nathaniel Gerlek' ],
[ 97, 'Andrea Gettys' ],
[ 98, 'Stephanie Gil Vega' ],
[ 99, 'Corwyn Giles' ],
[ 100, 'Bruce Arthur Gill' ],
[ 101, 'Samuel Giraud Carrier' ],
[ 102, 'Carter Gividen' ],
[ 103, 'Hunter Gonzales' ],
[ 104, 'Brandon Graham' ],
[ 105, 'Robert Greathouse' ],
[ 106, 'Kristian Green' ],
[ 107, 'Katherine Greer' ],
[ 108, 'Luke Grundvig' ],
[ 109, 'Andrew Gunyan' ],
[ 110, 'Elaina Hales' ],
[ 111, 'Spencer Hales' ],
[ 112, 'Andrew Hall' ],
[ 113, 'Cayson Hamilton' ],
[ 114, 'Carlee Hansen' ],
[ 115, 'Parker Hanson' ],
[ 116, 'Alex Harmon' ],
[ 117, 'Trevor Harmon' ],
[ 118, 'Olivia Harrison' ],
[ 119, 'Arvi Haxhillari' ],
[ 120, 'Grayden Hays' ],
[ 121, 'Merek Helmer' ],
[ 122, 'Joshua Hemmert' ],
[ 123, 'Bryce Hepner' ],
[ 124, 'Matthew Herron' ],
[ 125, 'Aubry Hiatt' ],
[ 126, 'David Higueros Lopez' ],
[ 127, 'Kate Hill' ],
[ 128, 'Lillian Mai Hill' ],
[ 129, 'Andrew Hillen' ],
[ 130, 'Austin Hillyard' ],
[ 131, 'Eden Hilson' ],
[ 132, 'Bailee Hodge' ],
[ 133, 'Travis Hoffman' ],
[ 134, 'Joshua Hunsaker' ],
[ 135, 'Dallin Hunter' ],
[ 136, 'Gavin Hunter' ],
[ 137, 'Sofia Iannicelli' ],
[ 138, 'Saba Iqbal' ],
[ 139, 'Benji Jackson' ],
[ 140, 'Amber Jarvi' ],
[ 141, 'Yu-Hsien Jen' ],
[ 142, 'Koby Jensen' ],
[ 143, 'Micah Perry Jensen' ],
[ 144, 'Andrew Jergensen' ],
[ 145, 'Jordan Johns' ],
[ 146, 'Charles Johnson' ],
[ 147, 'Colby Johnson' ],
[ 148, 'Cooper Johnston' ],
[ 149, 'Daniel Jones' ],
[ 150, 'Sam Jones' ],
[ 151, 'Chahyun Kang' ],
[ 152, 'Jiwoong Kang' ],
[ 153, 'Quinn Karpowitz' ],
[ 154, 'Carson Karren' ],
[ 155, 'Ben Kartchner' ],
[ 156, 'David Kartchner' ],
[ 157, 'Rai Katsuragawa' ],
[ 158, 'ANDREW Keele' ],
[ 159, 'Isaac Keenan' ],
[ 160, 'Leon Kendall' ],
[ 161, 'Alden Kim' ],
[ 162, 'Juneon Kim' ],
[ 163, 'Taehoon Kim' ],
[ 164, 'Josh Klingonsmith' ],
[ 165, 'Will Knisley' ],
[ 166, 'Huey Kolowich' ],
[ 167, 'Melissa Kretchmer' ],
[ 168, 'Ammon Kunzler' ],
[ 169, 'Jaden Kunzler' ],
[ 170, 'Ka Po Kwok' ],
[ 171, 'Stone Lai' ],
[ 172, 'Allison Lambert' ],
[ 173, 'Matt Larsen' ],
[ 174, 'Chase Larson' ],
[ 175, 'Bryce Lasson' ],
[ 176, 'Sean Last' ],
[ 177, 'Jacob Leavitt' ],
[ 178, 'Olivia Leavitt' ],
[ 179, 'Hanseul Lee' ],
[ 180, 'Jonghyuk Lee' ],
[ 181, 'Tiffany Lee' ],
[ 182, 'Eric Leech' ],
[ 183, 'Jeffrey Lewis' ],
[ 184, 'Nicholas Lewis' ],
[ 185, 'Bryson Lichtenberg' ],
[ 186, 'Kasey Lightheart' ],
[ 187, 'Bowen Liu' ],
[ 188, 'Braydon Lowe' ],
[ 189, 'Nathan Lunceford' ],
[ 190, 'Matthew Lund' ],
[ 191, 'Ben Madsen' ],
[ 192, 'Andrew Mam' ],
[ 193, 'Christopher Markstaller' ],
[ 194, 'Spencer Marshall' ],
[ 195, 'Aiden Martin' ],
[ 196, 'Maddie Mathis' ],
[ 197, 'Lizzy McClellan' ],
[ 198, 'Rhodric McCurdy' ],
[ 199, 'Logan McDonald' ],
[ 200, 'Blake McGhie' ],
[ 201, 'Megan McKeehan' ],
[ 202, 'Shayla McMillan' ],
[ 203, 'Todd Mehr' ],
[ 204, 'Will Melville' ],
[ 205, 'Samuel Mera Ricardo' ],
[ 206, 'Reid Merrell' ],
[ 207, 'Lizzie Merrill' ],
[ 208, 'Lacy Miller' ],
[ 209, 'Matthew Minson' ],
[ 210, 'Robert Morain' ],
[ 211, 'Ethan Moreno' ],
[ 212, 'Fritz-Carl Morlant' ],
[ 213, 'Kyler Moulton' ],
[ 214, 'Ty Mull' ],
[ 215, 'Kaden Mullin' ],
[ 216, 'Isaac Nash' ],
[ 217, 'Spencer Navas' ],
[ 218, 'Matthew Nelson' ],
[ 219, 'Connor Nesbit' ],
[ 220, 'Isaac Neuenschwander' ],
[ 221, 'Joshua Nielsen' ],
[ 222, 'Rebecca Ogden' ],
[ 223, 'Justin Olcott' ],
[ 224, 'John Olson' ],
[ 225, 'Marcus Omer' ],
[ 226, 'Lecio Orsi Ribeiro' ],
[ 227, 'Kayla Ou' ],
[ 228, 'Maximiliano Paris Gaete' ],
[ 229, 'Sungjin Park' ],
[ 230, 'Jordan Parr' ],
[ 231, 'Grace Pasion' ],
[ 232, 'Jordan Patton' ],
[ 233, 'Ethan Pedersen' ],
[ 234, 'Gabe Perry' ],
[ 235, 'Michael Peterson' ],
[ 236, 'James Phelps' ],
[ 237, 'Josh Phelps' ],
[ 238, 'David Pineda' ],
[ 239, 'MaiLia Pohahau' ],
[ 240, 'Nathan Prisbrey' ],
[ 241, 'Bernhardt Ramat' ],
[ 242, 'Andrew Redd' ],
[ 243, 'Sam Redd' ],
[ 244, 'Derek Reese' ],
[ 245, 'Tanner Reeve' ],
[ 246, 'Molly Remer' ],
[ 247, 'Adam Grant Rencher' ],
[ 248, 'Grant Rencher' ],
[ 249, 'Joshua Riley' ],
[ 250, 'German Rios-Lazo Arevalo' ],
[ 251, 'Ian Robertson' ],
[ 252, 'Andrew Rodabough' ],
[ 253, 'Jared Rodriguez' ],
[ 254, 'Mario Rodriguez Rodriguez' ],
[ 255, 'Samir Rodriguez Rodriguez' ],
[ 256, 'Curtis Rosenvall' ],
[ 257, 'Benson Rowley' ],
[ 258, 'Merica Rowley' ],
[ 259, 'Adam Rustad' ],
[ 260, 'Elijah Ryan' ],
[ 261, 'Tyler Sahagun' ],
[ 262, 'Nicholas Samson' ],
[ 263, 'Chad Sauder' ],
[ 264, 'Anson Savage' ],
[ 265, 'Porter Schollenberger' ],
[ 266, 'Calvin Seamons' ],
[ 267, 'Clayton Sharp' ],
[ 268, 'Megan Shellman' ],
[ 269, 'Matthew Sheppard' ],
[ 270, 'Dylan Shuldberg' ],
[ 271, 'Parker Shumard' ],
[ 272, 'Ammon Shurtz' ],
[ 273, 'Joan Siasoyco' ],
[ 274, 'Riley Sinema' ],
[ 275, 'Jonathan Skaggs' ],
[ 276, 'Andrew Slade' ],
[ 277, 'Johnny Slagle' ],
[ 278, 'Lindsay Slemboski' ],
[ 279, 'Peter Sloan' ],
[ 280, 'Brenden Smith' ],
[ 281, 'Evan Smith' ],
[ 282, 'Garrett Dickerson Smith' ],
[ 283, 'Savannah Smith' ],
[ 284, 'Seth Smurthwaite' ],
[ 285, 'Alex Snow' ],
[ 286, 'Yukina Soga' ],
[ 287, 'Jisu Song' ],
[ 288, 'Jack Sorensen' ],
[ 289, 'Lawry Sorenson' ],
[ 290, 'Samuel Soto' ],
[ 291, 'Garrett Southam' ],
[ 292, 'Matthias Southwick' ],
[ 293, 'Miles Spencer' ],
[ 294, 'Daniel Spiesman' ],
[ 295, 'Hannah Spigarelli' ],
[ 296, 'Kyle Standing' ],
[ 297, 'Aaron Starkweather' ],
[ 298, 'Jackson Stephens' ],
[ 299, 'Samuel Stewart' ],
[ 300, 'Hudson Stohl' ],
[ 301, 'Jennifer Stone' ],
[ 302, 'Junhao Su' ],
[ 303, 'Spencer Summerhays' ],
[ 304, 'Jeremy Summers' ],
[ 305, 'David Sumsion' ],
[ 306, 'Joshua Swartz' ],
[ 307, 'Anika Taylor' ],
[ 308, 'Benjamin Tessem' ],
[ 309, 'Michael Teuscher' ],
[ 310, 'Mackensey Thomason' ],
[ 311, 'Creed Thompson' ],
[ 312, 'Davin Thompson' ],
[ 313, 'Jonah Thurston' ],
[ 314, 'Teancum Tian' ],
[ 315, 'Andrew Tingey' ],
[ 316, 'Jaiden Tripp' ],
[ 317, 'Kaydance Turner' ],
[ 318, 'Sam Turner' ],
[ 319, 'Ben Tveten' ],
[ 320, 'Alexander Ueda' ],
[ 321, 'Mark Usevitch' ],
[ 322, 'Thomas Utrilla' ],
[ 323, 'Blaine Van Item' ],
[ 324, 'Piper Vasicek' ],
[ 325, 'Derek Vawdrey' ],
[ 326, 'Ethan Wagstaff' ],
[ 327, 'Ethan Wait' ],
[ 328, 'Brixtin Walker' ],
[ 329, 'Austin Warnick' ],
[ 330, 'Dallin Webecke' ],
[ 331, 'Trent Welling' ],
[ 332, 'Danika West' ],
[ 333, 'Kamea Wheeler' ],
[ 334, 'Landon Whitaker' ],
[ 335, 'Melvin Whitaker' ],
[ 336, 'Andrew Whiting' ],
[ 337, 'Tim Whiting' ],
[ 338, 'Max Whitney' ],
[ 339, 'Benjamin Wickham' ],
[ 340, 'Connor Wilhelm' ],
[ 341, 'Katie Willard' ],
[ 342, 'Devin Williams' ],
[ 343, 'Jacob Williams' ],
[ 344, 'Kaiden Williams' ],
[ 345, 'Skyler Williams' ],
[ 346, 'Harrison Winslow' ],
[ 347, 'Spencer Winward' ],
[ 348, 'Jacob Wise' ],
[ 349, 'Davis Wollesen' ],
[ 350, 'Kobey Workman' ],
[ 351, 'Sydne Wright' ],
[ 352, 'Jason Xing' ],
[ 353, 'Beau Yancey' ],
[ 354, 'Alec Yorgesen' ],
[ 355, 'Kevin Young' ],
]

const ControlsComponent = (): JSX.Element => {
  const [name, setName] = useState<string>("");

  const { sendMessage } = useMessaging<any>();

  const handleNameChange = (event: React.ChangeEvent<{ name?: string; value: string }>) => {
    const name = event.target.value;
    setName(name);
    sendMessage(name)
  };

  return (
    <div css={containerStyle}>
      <FormGroup>
        <p>
          <b>Pick your name from the list to see it on the big screen! (Your name will show for 60 seconds)</b>
        </p>
        <FormControl>
          <InputLabel htmlFor="name-native-helper">Name</InputLabel>
          <NativeSelect
            inputProps={{
              name: 'Name',
              id: 'name-native-helper',
            }}
            id="demo-simple-select"
            value={name}
            name="Name"
            onChange={handleNameChange}
          >
            <option value="all">All names</option>
            {
              names.map((name) => <option key={"id"} value={name[0]}>{name[1]}</option>)
            }
          </NativeSelect>
        </FormControl>
      </FormGroup>
    </div>
  );
};

export default ControlsComponent;
