/** @jsxImportSource @emotion/react */
import { css } from "@emotion/react";
import React, { useState } from "react";
import { useMessaging } from "@footron/controls-client";
import {
  FormControl,
  NativeSelect,
  InputLabel,
  Checkbox,
  FormControlLabel,
  FormGroup, Slider
} from "@material-ui/core";
import { useCallback } from "react";

const containerStyle = css`
  padding: 16px;
  overflow-x: hidden;

  p {
    margin: 0 0 16px;
  }
`;

const names = [
[ 0, 'Glenn Abernethy' ],
[ 1, 'Zachary Allen' ],
[ 2, 'Anton Alley' ],
[ 3, 'Makenna Allred' ],
[ 4, 'Stephen Amos' ],
[ 5, 'Anna Anderson' ],
[ 6, 'Jacob Anderson' ],
[ 7, 'Taylor Archibald' ],
[ 8, 'Bryson Armstrong' ],
[ 9, 'Brett Ashcraft' ],
[ 10, 'Jonah Austin' ],
[ 11, 'Austin Bailey' ],
[ 12, 'Tiberius Baker' ],
[ 13, 'Myles Barney' ],
[ 14, 'Quinn Barret' ],
[ 15, 'Jackson Baxter' ],
[ 16, 'Evan Bearman' ],
[ 17, 'Sam Bennion' ],
[ 18, 'Sam Berrey' ],
[ 19, 'Ivett Betlej' ],
[ 20, 'Trevor Bickmore' ],
[ 21, 'Cameron Birrell' ],
[ 22, 'Benjamin Bischoff' ],
[ 23, 'Brent Bishoff' ],
[ 24, 'Connor Blackburn' ],
[ 25, 'Cayden Blake' ],
[ 26, 'Spencer Blanchard' ],
[ 27, 'Diego Blaylock' ],
[ 28, 'Chase Bledsoe' ],
[ 29, 'Kyle Boden' ],
[ 30, 'Wes Bovee' ],
[ 31, 'McKay Bowcut' ],
[ 32, 'Brendon Bown' ],
[ 33, 'Michael Bradshaw' ],
[ 34, 'Taylor Bradshaw' ],
[ 35, 'Jason Brown' ],
[ 36, 'Greg Bullard' ],
[ 37, 'Nathan Bulloch' ],
[ 38, 'Tanner Buss' ],
[ 39, 'Jake Cahoon' ],
[ 40, 'Carson Call' ],
[ 41, 'Johnathan Call' ],
[ 42, 'Andrew Cambridge' ],
[ 43, 'Nathan Carter' ],
[ 44, 'Axel Castro-Romero' ],
[ 45, 'Josh Chambers' ],
[ 46, 'Venus Chan' ],
[ 47, 'Trisha Chandramouli' ],
[ 48, 'Evan Chase' ],
[ 49, 'Chris Chau' ],
[ 50, 'Jonah Checketts' ],
[ 51, 'Jaycelyn Chino' ],
[ 52, 'Brayden Christensen' ],
[ 53, 'Holden Clark' ],
[ 54, 'Harrison Cole' ],
[ 55, 'Thomas Cole' ],
[ 56, 'James Conners' ],
[ 57, 'Austin Cook' ],
[ 58, 'Hunter Corry' ],
[ 59, 'Mackenzie Cottle' ],
[ 60, 'Caleb Crandall' ],
[ 61, 'Hunter Crandall' ],
[ 62, 'Jacobus Crawford' ],
[ 63, 'Isaac James Criddle' ],
[ 64, 'Michael Croxall' ],
[ 65, 'Ben Cullen' ],
[ 66, 'Halsey Curry' ],
[ 67, 'Keiffer da Silva' ],
[ 68, 'Luke Dachenhausen' ],
[ 69, 'John Damon' ],
[ 70, 'Cody Daniels' ],
[ 71, 'Rebekah Daniels' ],
[ 72, 'Michael Davenport' ],
[ 73, 'Rebekah Dayton' ],
[ 74, 'Michael DeBuse' ],
[ 75, 'Hannah Decker' ],
[ 76, 'Jacob DeGraw' ],
[ 77, 'Alexander Densley' ],
[ 78, 'Porter Dickinson' ],
[ 79, 'DEZJARON Dorsey' ],
[ 80, 'Braden Dredge' ],
[ 81, 'Tyler Driggs' ],
[ 82, 'Jaysen Duckworth' ],
[ 83, 'Connor Dunn' ],
[ 84, 'Jeff Eardley' ],
[ 85, 'Nik Earl' ],
[ 86, 'Andi Ellis' ],
[ 87, 'Connor Ellis' ],
[ 88, 'Steven Elzinga' ],
[ 89, 'Ike Erdman' ],
[ 90, 'Rebekah Erikson' ],
[ 91, 'Zach Erikson' ],
[ 92, 'Landon Fackrell' ],
[ 93, 'Aaron Farr' ],
[ 94, 'Cannon Farr' ],
[ 95, 'Davi Fernandes' ],
[ 96, 'Joshua Fernelius' ],
[ 97, 'Maysen Fielding' ],
[ 98, 'James Finlinson' ],
[ 99, 'James Fitzgerald' ],
[ 100, 'Lauren Flanders' ],
[ 101, 'Minami Ford' ],
[ 102, 'Davis Forster' ],
[ 103, 'Devin Frandsen' ],
[ 104, 'Bronze Frazer' ],
[ 105, 'Peter Fullmer' ],
[ 106, 'Spencer Fund' ],
[ 107, 'David Gaag' ],
[ 108, 'Matthew Gabbitas' ],
[ 109, 'Jack Gashler' ],
[ 110, 'Rachel George' ],
[ 111, 'Zachary Getz' ],
[ 112, 'Matthew Glaus' ],
[ 113, 'Ammon Gleason' ],
[ 114, 'Layton Goeckeritz' ],
[ 115, 'Max Gollaher' ],
[ 116, 'Rachel Grant' ],
[ 117, 'Adam Griffin' ],
[ 118, 'Cassidy Grover' ],
[ 119, 'Sam Gwilliam' ],
[ 120, 'Mason Hamilton' ],
[ 121, 'Ash Hammond' ],
[ 122, 'Travis Blake Hansen' ],
[ 123, 'Parker Hanson' ],
[ 124, 'Caleb Harding' ],
[ 125, 'MaKenna Hardy' ],
[ 126, 'Trevor Harmon' ],
[ 127, 'Ryan Harper' ],
[ 128, 'Ammon Harps' ],
[ 129, 'Kyer Harris' ],
[ 130, 'Olivia Harrison' ],
[ 131, 'Allison Hart' ],
[ 132, 'Tanner Hartwell' ],
[ 133, 'Dakota Harward' ],
[ 134, 'Brendan Hatch' ],
[ 135, 'Daniel Hatch' ],
[ 136, 'Arvi Haxhillari' ],
[ 137, 'Brian Hayes' ],
[ 138, 'Mark Heilner' ],
[ 139, 'Josh Hendershot' ],
[ 140, 'Emma Henderson' ],
[ 141, 'Bryce Hepner' ],
[ 142, 'Tess Herrington' ],
[ 143, 'Tyler Hiatt' ],
[ 144, 'Caleb Hill' ],
[ 145, 'Andrew Hillen' ],
[ 146, 'Chloe Hilton' ],
[ 147, 'Khai Hirschi' ],
[ 148, 'Spencer Hodson' ],
[ 149, 'Brett Horman' ],
[ 150, 'Todd Hoskisson' ],
[ 151, 'Alden Howard' ],
[ 152, 'Peter Hu' ],
[ 153, 'Dallin Huff' ],
[ 154, 'Megan Huff' ],
[ 155, 'Jake Hunter' ],
[ 156, 'Noelle Hunter' ],
[ 157, 'Puneet Jain' ],
[ 158, 'Kevin James' ],
[ 159, 'Kimball Jardine' ],
[ 160, 'Aaron Jensen' ],
[ 161, 'Jordan Jensen' ],
[ 162, 'Ryan Jensen' ],
[ 163, 'Zachary Johnson' ],
[ 164, 'Braydon Jones' ],
[ 165, 'Daniel Jones' ],
[ 166, 'Dylan Jones' ],
[ 167, 'Jacob Jones' ],
[ 168, 'Keaweimoku Kaloi' ],
[ 169, 'Ryan Kane' ],
[ 170, 'Abby Kemp' ],
[ 171, 'Matthew Kennedy' ],
[ 172, 'Grace Kenny' ],
[ 173, 'KangJin Kim' ],
[ 174, 'Daniel Kingery' ],
[ 175, 'Ty Klabacka' ],
[ 176, 'Jakob Klobcic' ],
[ 177, 'Kelly Ko' ],
[ 178, 'Jake Kolander' ],
[ 179, 'Talin Kretchmer' ],
[ 180, 'Spencer Kunkel' ],
[ 181, 'Jonah Kunzler' ],
[ 182, 'Ka Po Kwok' ],
[ 183, 'David Lancaster' ],
[ 184, 'John Larsen' ],
[ 185, 'Alec Richard Larson' ],
[ 186, 'Hoon Lee' ],
[ 187, 'Jehyeon Lee' ],
[ 188, 'Brayden Lewis' ],
[ 189, 'Koby Lewis' ],
[ 190, 'Clara Li' ],
[ 191, 'George Li' ],
[ 192, 'Ruby Li' ],
[ 193, 'Bryson Lichtenberg' ],
[ 194, 'Yirang Lim' ],
[ 195, 'Ray Lin' ],
[ 196, 'Jason Lockard' ],
[ 197, 'Ethan Low' ],
[ 198, 'Joseph Lu' ],
[ 199, 'Benjamin Maduabuchi' ],
[ 200, 'Warren Mangum' ],
[ 201, 'Luke Marley' ],
[ 202, 'Anthony Marquez' ],
[ 203, 'Madelynn Martin' ],
[ 204, 'Joseph Mattson' ],
[ 205, 'Keanna McCrady' ],
[ 206, 'Mia McGuire' ],
[ 207, 'Austin McKamey' ],
[ 208, 'Megan McKeehan' ],
[ 209, 'Kimberly McKinnon' ],
[ 210, 'Austin McMaster' ],
[ 211, 'Andrea Melgoza' ],
[ 212, 'Samuel Mera Ricardo' ],
[ 213, 'Alex Mercer' ],
[ 214, 'Mason Miller' ],
[ 215, 'Scott Milner' ],
[ 216, 'Steven Mitchell' ],
[ 217, 'Tanner Montgomery' ],
[ 218, 'Jared Moon' ],
[ 219, 'Robert Morain' ],
[ 220, 'Stephen Kent Morgan' ],
[ 221, 'Drew Morris' ],
[ 222, 'Melissa Morris' ],
[ 223, 'Collin Morrison' ],
[ 224, 'Nathan Neilson' ],
[ 225, 'Haley Nelson' ],
[ 226, 'Joseph Nelson' ],
[ 227, 'Jacob Nienhuis' ],
[ 228, 'Parker Nilson' ],
[ 229, 'Haleigh Oeser' ],
[ 230, 'Jeff Olmo' ],
[ 231, 'Aaron Onstott' ],
[ 232, 'Logan Orr' ],
[ 233, 'Jay Orten' ],
[ 234, 'Jaclyn Palmer' ],
[ 235, 'Sungjin Park' ],
[ 236, 'Brandon Paul' ],
[ 237, 'Joseph Paulson' ],
[ 238, 'Benjamin Peek' ],
[ 239, 'William Pendleton' ],
[ 240, 'Jaren Petersen' ],
[ 241, 'Blake Peterson' ],
[ 242, 'Tyson Peterson' ],
[ 243, 'Elijah Casey Pettitt' ],
[ 244, 'Timothy Pitts' ],
[ 245, 'Kayler Pope' ],
[ 246, 'Tyler Porter' ],
[ 247, 'Taj Poulsen' ],
[ 248, 'Elaine Prathiksha' ],
[ 249, 'Benson Probst' ],
[ 250, 'Brandon Pulsipher' ],
[ 251, 'Takun Purba' ],
[ 252, 'Preston Raab' ],
[ 253, 'Bernhardt Ramat' ],
[ 254, 'Juan Carlos Rangel Barco' ],
[ 255, 'Brock Rawson' ],
[ 256, 'Briggs Reed' ],
[ 257, 'Seth Remer' ],
[ 258, 'Adam Rice' ],
[ 259, 'Brady Richardson' ],
[ 260, 'Philip Richey' ],
[ 261, 'Freddy Rios' ],
[ 262, 'Nathan Roberts' ],
[ 263, 'Chance Robinson' ],
[ 264, 'Jared Rodriguez' ],
[ 265, 'Mario Rodriguez Rodriguez' ],
[ 266, 'Tad Rosenberg' ],
[ 267, 'Curtis Rosenvall' ],
[ 268, 'Adam Rounsville' ],
[ 269, 'Kenneth Salomonson' ],
[ 270, 'Elias Sanabria' ],
[ 271, 'Chad Sauder' ],
[ 272, 'Grayson Schmalz' ],
[ 273, 'Nelson Schnepf' ],
[ 274, 'Tyler Seegmiller' ],
[ 275, 'Noah Seneca' ],
[ 276, 'Ben Shafer' ],
[ 277, 'Clayton Sharp' ],
[ 278, 'Joey Sherrill' ],
[ 279, 'Nathan Sirrine' ],
[ 280, 'Jonathan Skaggs' ],
[ 281, 'Brigham Skarda' ],
[ 282, 'Nate Skonnard' ],
[ 283, 'Johnny Slagle' ],
[ 284, 'Sarah Smalley' ],
[ 285, 'Garrett Dickerson Smith' ],
[ 286, 'Nicholas Hyrum Smith' ],
[ 287, 'Savannah Smith' ],
[ 288, 'Sterling Smith' ],
[ 289, 'Taylor Smith' ],
[ 290, 'McKay Snell' ],
[ 291, 'Young Woo Song' ],
[ 292, 'Ty Sorensen' ],
[ 293, 'Garrett Southam' ],
[ 294, 'Alek Spackman' ],
[ 295, 'Jacob Speakman' ],
[ 296, 'Jaden Spotten' ],
[ 297, 'Kyle Standing' ],
[ 298, 'Nathen Stark' ],
[ 299, 'Jaden Sterner' ],
[ 300, 'John Stewart' ],
[ 301, 'Matthew Stutzman' ],
[ 302, 'Gary Suarez Zabala' ],
[ 303, 'Helaman Sung' ],
[ 304, 'Cole Sutton' ],
[ 305, 'Justin Tackett' ],
[ 306, 'Ishmael Taleo' ],
[ 307, 'John Tappen' ],
[ 308, 'Anika Taylor' ],
[ 309, 'Daniel Terry' ],
[ 310, 'Haile Terry' ],
[ 311, 'Eric Thomas' ],
[ 312, 'Cordell Thompson' ],
[ 313, 'David Thompson' ],
[ 314, 'Isaac Thompson' ],
[ 315, 'Brent Thomson' ],
[ 316, 'Matthew Thorin' ],
[ 317, 'Molly Thornton' ],
[ 318, 'Teancum Tian' ],
[ 319, 'Tyler Timothy' ],
[ 320, 'Andrew Tingey' ],
[ 321, 'Marcus Tracy' ],
[ 322, 'Jacob Trader' ],
[ 323, 'Hannah Tran' ],
[ 324, 'Rebekah Tran' ],
[ 325, 'Toren Trauntvein' ],
[ 326, 'Tyler Trommlitz' ],
[ 327, 'Ben Tveten' ],
[ 328, 'Warda Usman' ],
[ 329, 'Erik Vagil' ],
[ 330, 'Garrett Vance' ],
[ 331, 'Sam Vance' ],
[ 332, 'Piper Vasicek' ],
[ 333, 'Ethan Taylor Walch' ],
[ 334, 'Bryce Wall' ],
[ 335, 'Sarah Ward' ],
[ 336, 'Conner Wattles' ],
[ 337, 'David Weatherford' ],
[ 338, 'Collin Webb' ],
[ 339, 'Dallin Webecke' ],
[ 340, 'Jazz Weller' ],
[ 341, 'Hayden Welton' ],
[ 342, 'Sophie Welton' ],
[ 343, 'Angel Wheelwright' ],
[ 344, 'Garett Whimple' ],
[ 345, 'Ethan Williams' ],
[ 346, 'Olivia Wilson' ],
[ 347, 'Josh Wiseman' ],
[ 348, 'Walker Wolfgramm' ],
[ 349, 'Grace Wong' ],
[ 350, 'Jared Wood' ],
[ 351, 'Jeffry Yoon' ],
[ 352, 'Stuart Yorgason' ],
[ 353, 'Zach York' ],
[ 354, 'Spencer Young' ],
[ 355, 'Hao Yu' ],
[ 356, 'Aaron Zelenski' ],
[ 357, 'Tong Zhou' ],
[ 358, 'Chase Zundel' ],

]

const ControlsComponent = (): JSX.Element => {
  const [name, setName] = useState<string>("");

  const { sendMessage } = useMessaging<any>();

  const handleNameChange = (event: React.ChangeEvent<{ name?: string; value: string }>) => {
    const name = event.target.value;
    setName(name);
    sendMessage(name)
  };

  return (
    <div css={containerStyle}>
      <FormGroup>
        <p>
          <b>Pick your name from the list to see it on the big screen! (Your name will show for 60 seconds)</b>
        </p>
        <FormControl>
          <InputLabel htmlFor="name-native-helper">Name</InputLabel>
          <NativeSelect
            inputProps={{
              name: 'Name',
              id: 'name-native-helper',
            }}
            id="demo-simple-select"
            value={name}
            name="Name"
            onChange={handleNameChange}
          >
            <option value="all">All names</option>
            {
              names.map((name) => <option key={"id"} value={name[0]}>{name[1]}</option>)
            }
          </NativeSelect>
        </FormControl>
      </FormGroup>
    </div>
  );
};

export default ControlsComponent;
